# Exported from Render on 2025-11-29T01:44:42Z
version: "1"
projects:
- name: Flow RMS Services
  environments:
  - name: Staging
    networking:
      isolation: enabled
    services:
    - type: web
      name: flow-connect-frontend
      runtime: node
      repo: https://github.com/FlowRMS/flow-connect-frontend-new
      plan: starter
      envVars:
      - key: PORT
        sync: false
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: "--max-old-space-size=2048"
      region: ohio
      buildCommand: npm ci --legacy-peer-deps && npm run build
      startCommand: npm run start
      autoDeployTrigger: commit
