/**
 * Dashboard Mock Data
 */

import type { Activity } from './types';

export const mockActivities: Activity[] = [
  {
    type: 'job',
    title: 'New Job: Downtown Plaza Renovation',
    time: '15m ago',
    date: '11/21/2024',
    description: 'Large-scale commercial lighting project with Turner Construction',
    entity: 'Downtown Plaza Renovation',
    entityType: 'Job',
    tags: ['Lighting', 'Commercial'],
    assignedTo: 'Sarah Johnson',
    mentions: ['@Turner Construction', '@Miller Electric'],
    likes: 2,
    comments: 3,
    activityStatus: 'upcoming',
    link: '/jobs',
  },
  {
    type: 'call',
    title: 'Call with Marcus Chen',
    time: '30m ago',
    date: '11/21/2024',
    description: 'Discussed lighting specs for Downtown Plaza project',
    entity: 'Downtown Plaza Renovation',
    entityType: 'Job',
    tags: ['Lighting', 'Follow-up'],
    assignedTo: 'Sarah Johnson',
    mentions: ['@Turner Construction', '@Miller Electric'],
    likes: 2,
    comments: 3,
    activityStatus: 'upcoming',
    link: '/jobs',
  },
  {
    type: 'pre-opportunity',
    title: 'New Pre-Opportunity: TechCorp HQ Expansion',
    time: '1h ago',
    date: '11/21/2024',
    description: 'HVAC controls system upgrade for corporate headquarters',
    entity: 'TechCorp HQ Expansion',
    entityType: 'Pre-Opportunity',
    tags: ['Quote', 'HVAC'],
    assignedTo: 'Marcus Chen',
    mentions: [],
    likes: 1,
    comments: 0,
    activityStatus: 'upcoming',
    link: '/pre-opportunities',
  },
  {
    type: 'email',
    title: 'Email sent to Sarah Johnson',
    time: '1.5h ago',
    date: '11/21/2024',
    description: 'Quote follow-up for HVAC controls',
    entity: 'TechCorp HQ Expansion',
    entityType: 'Pre-Opportunity',
    tags: ['Quote', 'HVAC'],
    assignedTo: 'Marcus Chen',
    mentions: [],
    likes: 1,
    comments: 0,
    activityStatus: 'upcoming',
    link: '/pre-opportunities',
  },
  {
    type: 'note',
    title: 'Note added to Riverside Medical',
    time: '2h ago',
    date: '11/20/2024',
    description: 'Engineer prefers manufacturer spec over alternates',
    entity: 'Riverside Medical Center',
    entityType: 'Job',
    tags: ['Engineering', 'Specifications'],
    assignedTo: 'Sarah Johnson',
    mentions: ['@McCarthy Building'],
    likes: 3,
    comments: 2,
    activityStatus: 'completed',
    link: '/notes',
  },
  {
    type: 'meeting',
    title: 'Site visit scheduled',
    time: '3h ago',
    date: '11/20/2024',
    description: 'Meeting with GC and EC next Tuesday at 10am',
    entity: 'Harbor View Apartments',
    entityType: 'Job',
    tags: ['Site Visit', 'Coordination'],
    assignedTo: 'David Torres',
    mentions: [],
    likes: 0,
    comments: 1,
    activityStatus: 'completed',
    link: '/jobs',
  },
  {
    type: 'task',
    title: 'Task completed',
    time: '4h ago',
    date: '11/20/2024',
    description: 'Submitted bid package to distributor',
    entity: 'University Lab Building',
    entityType: 'Job',
    tags: ['Bidding', 'Completed'],
    assignedTo: 'Marcus Chen',
    mentions: [],
    likes: 2,
    comments: 1,
    activityStatus: 'completed',
    link: '/tasks',
  },
  {
    type: 'contact',
    title: 'New Contact: David Park',
    time: '5h ago',
    date: '11/19/2024',
    description: 'Facility manager at Green Valley Office Park',
    entity: 'David Park',
    entityType: 'Contact',
    tags: ['Facility Manager', 'New Lead'],
    assignedTo: 'Sarah Johnson',
    mentions: [],
    likes: 1,
    comments: 1,
    activityStatus: 'completed',
    link: '/contacts',
  },
  {
    type: 'email',
    title: 'Email received from David Park',
    time: '5.5h ago',
    date: '11/19/2024',
    description: 'Request for pricing on additional zones',
    entity: 'Green Valley Office Park',
    entityType: 'Contact',
    tags: ['Pricing', 'Inquiry'],
    assignedTo: 'Sarah Johnson',
    mentions: [],
    likes: 0,
    comments: 0,
    activityStatus: 'completed',
    link: '/contacts',
  },
  {
    type: 'note',
    title: 'Note added to Metro Transit Hub',
    time: '6h ago',
    date: '11/19/2024',
    description: 'Project timeline moved up by 2 weeks per client request',
    entity: 'Metro Transit Hub',
    entityType: 'Job',
    tags: ['Timeline', 'Urgent'],
    assignedTo: 'David Torres',
    mentions: [],
    likes: 4,
    comments: 5,
    activityStatus: 'completed',
    link: '/notes',
  },
  {
    type: 'call',
    title: 'Call with Jennifer Wilson',
    time: '7h ago',
    date: '11/18/2024',
    description: 'Clarified installation schedule and crew requirements',
    entity: 'Westside Retail Center',
    entityType: 'Contact',
    tags: ['Installation', 'Coordination'],
    assignedTo: 'Marcus Chen',
    mentions: [],
    likes: 1,
    comments: 2,
    activityStatus: 'completed',
    link: '/contacts',
  },
  {
    type: 'task',
    title: 'Task completed',
    time: '8h ago',
    date: '11/18/2024',
    description: 'Updated BOM with approved substitutions',
    entity: 'Oak Street Condos',
    entityType: 'Job',
    tags: ['BOM', 'Documentation'],
    assignedTo: 'Sarah Johnson',
    mentions: [],
    likes: 2,
    comments: 0,
    activityStatus: 'completed',
    link: '/tasks',
  },
  {
    type: 'meeting',
    title: 'Project kickoff scheduled',
    time: '9h ago',
    date: '11/17/2024',
    description: 'Team meeting set for Monday 9am with all stakeholders',
    entity: 'Innovation Campus Phase 2',
    entityType: 'Job',
    tags: ['Kickoff', 'Planning'],
    assignedTo: 'Sarah Johnson',
    mentions: [],
    likes: 3,
    comments: 4,
    activityStatus: 'completed',
    link: '/jobs',
  },
  {
    type: 'email',
    title: 'Email sent to Robert Martinez',
    time: '10h ago',
    date: '11/17/2024',
    description: 'Forwarded technical drawings for approval',
    entity: 'City Hall Renovation',
    entityType: 'Job',
    tags: ['Drawings', 'Approval'],
    assignedTo: 'David Torres',
    mentions: [],
    likes: 1,
    comments: 1,
    activityStatus: 'completed',
    link: '/jobs',
  },
  {
    type: 'note',
    title: 'Note added to Lakefront Hotel',
    time: '11h ago',
    date: '11/16/2024',
    description: 'Client requested energy efficiency upgrade options',
    entity: 'Lakefront Hotel',
    entityType: 'Pre-Opportunity',
    tags: ['Energy', 'Opportunity'],
    assignedTo: 'Marcus Chen',
    mentions: ['@Green Energy Solutions'],
    likes: 2,
    comments: 3,
    activityStatus: 'completed',
    link: '/notes',
  },
  {
    type: 'call',
    title: 'Call with Amanda Foster',
    time: '12h ago',
    date: '11/16/2024',
    description: 'Discussed warranty terms and service agreements',
    entity: 'Summit Medical Plaza',
    entityType: 'Contact',
    tags: ['Warranty', 'Service'],
    assignedTo: 'Sarah Johnson',
    mentions: [],
    likes: 0,
    comments: 1,
    activityStatus: 'completed',
    link: '/contacts',
  },
];
