// ============================================================================
// Flow Submittals - Mock Data
// ============================================================================
// This mock data integrates with existing quotes, jobs, and manufacturers

import type {
  Submittal,
  SubmittalItem,
  SpecSheet,
  SpecSheetFolder,
  HighlightDefinition,
  HighlightRegion,
  SubmittalRevision,
  SubmittalStakeholder,
  SubmittalSummary,
  ReturnedPdf,
  ChangeAnalysis,
  ItemChange,
  EmailSendRecord,
} from '../types/submittals';
import { defaultSubmittalConfig } from '../types/submittals';

// -----------------------------------------------------------------------------
// Spec Sheet Folders
// -----------------------------------------------------------------------------

export const mockSpecSheetFolders: SpecSheetFolder[] = [
  // Acuity Brands folders
  {
    id: 'FLD-001',
    name: 'Linear',
    parentId: null,
    manufacturer: 'Acuity Brands',
    isAutoGenerated: true,
    createdAt: '2024-01-15T10:00:00Z',
    createdBy: 'System',
  },
  {
    id: 'FLD-002',
    name: 'Downlights',
    parentId: null,
    manufacturer: 'Acuity Brands',
    isAutoGenerated: true,
    createdAt: '2024-01-15T10:00:00Z',
    createdBy: 'System',
  },
  {
    id: 'FLD-003',
    name: 'Track',
    parentId: null,
    manufacturer: 'Acuity Brands',
    isAutoGenerated: true,
    createdAt: '2024-01-15T10:00:00Z',
    createdBy: 'System',
  },
  {
    id: 'FLD-004',
    name: 'Outdoor',
    parentId: null,
    manufacturer: 'Acuity Brands',
    isAutoGenerated: true,
    createdAt: '2024-01-15T10:00:00Z',
    createdBy: 'System',
  },
  {
    id: 'FLD-005',
    name: 'Emergency & Exit',
    parentId: null,
    manufacturer: 'Acuity Brands',
    isAutoGenerated: true,
    createdAt: '2024-01-15T10:00:00Z',
    createdBy: 'System',
  },
  // Lutron folders
  {
    id: 'FLD-006',
    name: 'Dimmers',
    parentId: null,
    manufacturer: 'Lutron',
    isAutoGenerated: true,
    createdAt: '2024-01-20T10:00:00Z',
    createdBy: 'System',
  },
  {
    id: 'FLD-007',
    name: 'Control Systems',
    parentId: null,
    manufacturer: 'Lutron',
    isAutoGenerated: true,
    createdAt: '2024-01-20T10:00:00Z',
    createdBy: 'System',
  },
  // User-created nested folder
  {
    id: 'FLD-008',
    name: 'High Wattage',
    parentId: 'FLD-001',
    manufacturer: 'Acuity Brands',
    isAutoGenerated: false,
    createdAt: '2024-02-01T10:00:00Z',
    createdBy: 'Sarah Chen',
  },
];

// -----------------------------------------------------------------------------
// Spec Sheets (Cut Sheets) Library
// -----------------------------------------------------------------------------

export const mockSpecSheets: SpecSheet[] = [
  // Acuity Brands
  {
    id: 'SS-001',
    manufacturer: 'Acuity Brands',
    fileName: 'lithonia-lx-4500-series.pdf',
    displayName: 'Lithonia LX-4500 Series Linear LED',
    categories: ['indoor'],
    tags: ['LED', '4ft', '5000K', 'High Output'],
    folderId: 'FLD-008',
    uploadSource: 'url',
    sourceUrl: 'https://acuitybrands.com/specs/lx-4500.pdf',
    fileUrl: '/spec-sheets/lithonia-lx-4500-series.pdf',
    fileSize: 2458624,
    pageCount: 4,
    uploadedAt: '2024-01-15T10:30:00Z',
    uploadedBy: 'Sarah Chen',
    needsReview: false,
    usageCount: 12,
    highlightCount: 3,
  },
  {
    id: 'SS-002',
    manufacturer: 'Acuity Brands',
    fileName: 'lithonia-lx-2200-recessed.pdf',
    displayName: 'Lithonia LX-2200 Recessed Downlight',
    categories: ['indoor'],
    tags: ['LED', '6 inch', '3000K', 'Dimmable'],
    folderId: 'FLD-002',
    uploadSource: 'url',
    sourceUrl: 'https://acuitybrands.com/specs/lx-2200.pdf',
    fileUrl: '/spec-sheets/lithonia-lx-2200-recessed.pdf',
    fileSize: 1843200,
    pageCount: 3,
    uploadedAt: '2024-01-18T14:22:00Z',
    uploadedBy: 'Sarah Chen',
    needsReview: false,
    usageCount: 8,
    highlightCount: 2,
  },
  {
    id: 'SS-003',
    manufacturer: 'Acuity Brands',
    fileName: 'lithonia-trk-led-track.pdf',
    displayName: 'Lithonia TRK-LED Track Lighting',
    categories: ['indoor', 'decorative'],
    tags: ['LED', 'Track', 'Adjustable', '30W'],
    folderId: 'FLD-003',
    uploadSource: 'file',
    fileUrl: '/spec-sheets/lithonia-trk-led-track.pdf',
    fileSize: 3145728,
    pageCount: 6,
    uploadedAt: '2024-02-05T09:15:00Z',
    uploadedBy: 'Marcus Chen',
    needsReview: false,
    usageCount: 5,
    highlightCount: 1,
  },
  {
    id: 'SS-004',
    manufacturer: 'Acuity Brands',
    fileName: 'holophane-outdoor-area.pdf',
    displayName: 'Holophane Outdoor Area Lighting',
    categories: ['outdoor'],
    tags: ['LED', 'Area Light', 'Parking', 'IP65'],
    folderId: 'FLD-004',
    uploadSource: 'url',
    sourceUrl: 'https://acuitybrands.com/specs/holophane-outdoor.pdf',
    fileUrl: '/spec-sheets/holophane-outdoor-area.pdf',
    fileSize: 4194304,
    pageCount: 8,
    uploadedAt: '2024-02-10T11:00:00Z',
    uploadedBy: 'Sarah Chen',
    needsReview: false,
    usageCount: 3,
    highlightCount: 0,
  },
  // Lutron
  {
    id: 'SS-005',
    manufacturer: 'Lutron',
    fileName: 'lutron-plx-200-dimmer.pdf',
    displayName: 'Lutron PLX-200 Programmable Dimmer',
    categories: ['controls'],
    tags: ['Dimmer', 'Programmable', 'Daylight Harvesting'],
    folderId: 'FLD-006',
    uploadSource: 'url',
    sourceUrl: 'https://lutron.com/specs/plx-200.pdf',
    fileUrl: '/spec-sheets/lutron-plx-200-dimmer.pdf',
    fileSize: 2097152,
    pageCount: 4,
    uploadedAt: '2024-01-20T15:45:00Z',
    uploadedBy: 'David Torres',
    needsReview: false,
    usageCount: 15,
    highlightCount: 4,
  },
  {
    id: 'SS-006',
    manufacturer: 'Lutron',
    fileName: 'lutron-grafik-eye-qs.pdf',
    displayName: 'Lutron GRAFIK Eye QS Control',
    categories: ['controls'],
    tags: ['Control System', 'Wireless', 'Scene Control'],
    folderId: 'FLD-007',
    uploadSource: 'url',
    sourceUrl: 'https://lutron.com/specs/grafik-eye-qs.pdf',
    fileUrl: '/spec-sheets/lutron-grafik-eye-qs.pdf',
    fileSize: 3670016,
    pageCount: 12,
    uploadedAt: '2024-02-01T10:00:00Z',
    uploadedBy: 'David Torres',
    needsReview: false,
    usageCount: 7,
    highlightCount: 2,
  },
  // Leviton
  {
    id: 'SS-007',
    manufacturer: 'Leviton',
    fileName: 'leviton-dimmer-switches.pdf',
    displayName: 'Leviton Decora Dimmer Switches',
    categories: ['controls'],
    tags: ['Dimmer', '600W', 'Residential'],
    uploadSource: 'file',
    fileUrl: '/spec-sheets/leviton-dimmer-switches.pdf',
    fileSize: 1572864,
    pageCount: 3,
    uploadedAt: '2024-01-25T09:30:00Z',
    uploadedBy: 'Marcus Chen',
    needsReview: false,
    usageCount: 6,
    highlightCount: 2,
  },
  // Philips/Signify
  {
    id: 'SS-008',
    manufacturer: 'Philips',
    fileName: 'philips-pendant-modern.pdf',
    displayName: 'Philips Modern Pendant Series',
    categories: ['indoor', 'decorative'],
    tags: ['Pendant', 'Decorative', '18 inch'],
    uploadSource: 'url',
    sourceUrl: 'https://signify.com/specs/pendant-modern.pdf',
    fileUrl: '/spec-sheets/philips-pendant-modern.pdf',
    fileSize: 2621440,
    pageCount: 5,
    uploadedAt: '2024-02-12T14:00:00Z',
    uploadedBy: 'Sarah Chen',
    needsReview: true,
    usageCount: 4,
    highlightCount: 1,
  },
  // Waldmann (from the existing submittals tab)
  {
    id: 'SS-009',
    manufacturer: 'Waldmann',
    fileName: 'waldmann-task-lighting.pdf',
    displayName: 'Waldmann Task Lighting Series',
    categories: ['indoor', 'industrial'],
    tags: ['Task Light', 'Adjustable Arm', 'Lab', 'Industrial'],
    uploadSource: 'url',
    sourceUrl: 'https://waldmann.com/specs/task-lighting.pdf',
    fileUrl: '/spec-sheets/waldmann-task-lighting.pdf',
    fileSize: 1966080,
    pageCount: 4,
    uploadedAt: '2024-02-20T11:30:00Z',
    uploadedBy: 'David Torres',
    needsReview: false,
    usageCount: 2,
    highlightCount: 0,
  },
  // Industrial - Drives
  {
    id: 'SS-010',
    manufacturer: 'ABB',
    fileName: 'abb-acs580-drives.pdf',
    displayName: 'ABB ACS580 General Purpose Drives',
    categories: ['drives', 'industrial'],
    tags: ['VFD', 'Motor Control', 'Industrial'],
    uploadSource: 'url',
    sourceUrl: 'https://abb.com/specs/acs580.pdf',
    fileUrl: '/spec-sheets/abb-acs580-drives.pdf',
    fileSize: 5242880,
    pageCount: 16,
    uploadedAt: '2024-02-25T10:00:00Z',
    uploadedBy: 'Marcus Chen',
    needsReview: false,
    usageCount: 3,
    highlightCount: 1,
  },
  // Emergency
  {
    id: 'SS-011',
    manufacturer: 'Acuity Brands',
    fileName: 'lithonia-emergency-exit.pdf',
    displayName: 'Lithonia Emergency & Exit Signs',
    categories: ['emergency', 'indoor'],
    tags: ['Emergency', 'Exit Sign', 'Battery Backup', 'LED'],
    folderId: 'FLD-005',
    uploadSource: 'file',
    fileUrl: '/spec-sheets/lithonia-emergency-exit.pdf',
    fileSize: 2097152,
    pageCount: 6,
    uploadedAt: '2024-03-01T09:00:00Z',
    uploadedBy: 'Sarah Chen',
    needsReview: false,
    usageCount: 9,
    highlightCount: 3,
  },
  // Sports Lighting
  {
    id: 'SS-012',
    manufacturer: 'Musco',
    fileName: 'musco-tl-sports-lighting.pdf',
    displayName: 'Musco TLC for LED Sports Lighting',
    categories: ['outdoor', 'sports_lighting'],
    tags: ['Sports', 'Stadium', 'High Power', 'LED'],
    uploadSource: 'url',
    sourceUrl: 'https://musco.com/specs/tlc-led.pdf',
    fileUrl: '/spec-sheets/musco-tl-sports-lighting.pdf',
    fileSize: 8388608,
    pageCount: 24,
    uploadedAt: '2024-03-05T14:30:00Z',
    uploadedBy: 'David Torres',
    needsReview: false,
    usageCount: 1,
    highlightCount: 0,
  },
];

// -----------------------------------------------------------------------------
// Highlight Definitions
// -----------------------------------------------------------------------------

export const mockHighlightDefinitions: HighlightDefinition[] = [
  // LX-4500-LED highlights on SS-001
  {
    id: 'HD-001',
    specSheetId: 'SS-001',
    catalogNumber: 'LX-4500-LED',
    manufacturer: 'Acuity Brands',
    regions: [
      {
        id: 'HR-001',
        pageNumber: 1,
        x: 15,
        y: 25,
        width: 70,
        height: 8,
        shape: 'highlight',
        color: '#FFEB3B',
      },
      {
        id: 'HR-002',
        pageNumber: 2,
        x: 10,
        y: 40,
        width: 35,
        height: 5,
        shape: 'rectangle',
        color: '#FF5722',
        strokeWidth: 2,
      },
    ],
    createdAt: '2024-01-20T10:00:00Z',
    createdBy: 'Sarah Chen',
    updatedAt: '2024-02-15T14:30:00Z',
    updatedBy: 'Sarah Chen',
  },
  // PLX-200-DIM highlights on SS-005
  {
    id: 'HD-002',
    specSheetId: 'SS-005',
    catalogNumber: 'PLX-200-DIM',
    manufacturer: 'Lutron',
    regions: [
      {
        id: 'HR-003',
        pageNumber: 1,
        x: 20,
        y: 30,
        width: 60,
        height: 10,
        shape: 'highlight',
        color: '#FFEB3B',
      },
      {
        id: 'HR-004',
        pageNumber: 3,
        x: 25,
        y: 55,
        width: 50,
        height: 15,
        shape: 'rectangle',
        color: '#4CAF50',
        strokeWidth: 2,
      },
    ],
    createdAt: '2024-01-22T11:00:00Z',
    createdBy: 'David Torres',
    updatedAt: '2024-01-22T11:00:00Z',
    updatedBy: 'David Torres',
  },
  // LX-2200-REC highlights on SS-002
  {
    id: 'HD-003',
    specSheetId: 'SS-002',
    catalogNumber: 'LX-2200-REC',
    manufacturer: 'Acuity Brands',
    regions: [
      {
        id: 'HR-005',
        pageNumber: 1,
        x: 12,
        y: 35,
        width: 75,
        height: 6,
        shape: 'highlight',
        color: '#FFEB3B',
      },
    ],
    createdAt: '2024-02-01T09:00:00Z',
    createdBy: 'Sarah Chen',
    updatedAt: '2024-02-01T09:00:00Z',
    updatedBy: 'Sarah Chen',
  },
  // TRK-LED-30W highlights on SS-003
  {
    id: 'HD-004',
    specSheetId: 'SS-003',
    catalogNumber: 'TRK-LED-30W',
    manufacturer: 'Acuity Brands',
    regions: [
      {
        id: 'HR-006',
        pageNumber: 2,
        x: 18,
        y: 42,
        width: 64,
        height: 8,
        shape: 'highlight',
        color: '#FFEB3B',
      },
      {
        id: 'HR-007',
        pageNumber: 2,
        x: 60,
        y: 20,
        width: 25,
        height: 12,
        shape: 'oval',
        color: '#E91E63',
        strokeWidth: 2,
      },
    ],
    createdAt: '2024-02-10T15:00:00Z',
    createdBy: 'Marcus Chen',
    updatedAt: '2024-02-10T15:00:00Z',
    updatedBy: 'Marcus Chen',
  },
  // Emergency exit highlights
  {
    id: 'HD-005',
    specSheetId: 'SS-011',
    catalogNumber: 'EX-200-LED',
    manufacturer: 'Acuity Brands',
    regions: [
      {
        id: 'HR-008',
        pageNumber: 1,
        x: 10,
        y: 20,
        width: 80,
        height: 5,
        shape: 'highlight',
        color: '#FFEB3B',
      },
    ],
    createdAt: '2024-03-05T10:00:00Z',
    createdBy: 'Sarah Chen',
    updatedAt: '2024-03-05T10:00:00Z',
    updatedBy: 'Sarah Chen',
  },
];

// -----------------------------------------------------------------------------
// Stakeholders (pulled from existing contacts)
// -----------------------------------------------------------------------------

const stakeholders: {
  engineers: SubmittalStakeholder[];
  architects: SubmittalStakeholder[];
  customers: SubmittalStakeholder[];
} = {
  engineers: [
    {
      contactId: 'CON-ENG-001',
      contactName: 'Michael Rodriguez',
      companyName: 'MEP Engineering Associates',
      email: 'mrodriguez@mepeng.com',
      role: 'engineer',
    },
    {
      contactId: 'CON-ENG-002',
      contactName: 'Jennifer Walsh',
      companyName: 'Syska Hennessy Group',
      email: 'jwalsh@syska.com',
      role: 'engineer',
    },
  ],
  architects: [
    {
      contactId: 'CON-ARCH-001',
      contactName: 'Robert Kim',
      companyName: 'HKS Architects',
      email: 'rkim@hks.com',
      role: 'architect',
    },
    {
      contactId: 'CON-ARCH-002',
      contactName: 'Amanda Foster',
      companyName: 'Gensler',
      email: 'amanda.foster@gensler.com',
      role: 'architect',
    },
  ],
  customers: [
    {
      contactId: 'CON-GC-001',
      contactName: 'James Patterson',
      companyName: 'Turner Construction',
      email: 'jpatterson@turner.com',
      role: 'gc',
    },
    {
      contactId: 'CON-GC-002',
      contactName: 'Lisa Chen',
      companyName: 'Hensel Phelps',
      email: 'lchen@henselphelps.com',
      role: 'gc',
    },
    {
      contactId: 'CON-DIST-001',
      contactName: 'Mark Thompson',
      companyName: 'Graybar Electric',
      email: 'mthompson@graybar.com',
      role: 'customer',
    },
  ],
};

// -----------------------------------------------------------------------------
// Submittals
// -----------------------------------------------------------------------------

export const mockSubmittals: Submittal[] = [
  // Submittal 1: Downtown Medical Center (from Q-2024-001)
  {
    id: 'SUB-001',
    jobId: 'J-001',
    jobName: 'Downtown Medical Center',
    jobLocation: '450 Medical Parkway, Austin, TX 78701',
    quoteIds: ['Q-2024-001'],
    customers: [stakeholders.customers[0], stakeholders.customers[2]],
    engineers: [stakeholders.engineers[0]],
    architects: [stakeholders.architects[0]],
    bidDate: '2024-04-15',
    submittalDate: '2024-03-25',
    createdAt: '2024-03-20T10:00:00Z',
    updatedAt: '2024-03-25T14:30:00Z',
    status: 'for_approval',
    currentRevision: 1,
    items: [
      {
        id: 'SI-001',
        submittalId: 'SUB-001',
        quoteLineItemId: 'LI-001',
        quoteId: 'Q-2024-001',
        fixtureType: 'F1',
        manufacturer: 'Acuity Brands',
        catalogNumber: 'LX-4500-LED',
        description: 'Linear LED Fixture 4ft 5000K with Integrated Driver',
        quantity: 150,
        specSheetId: 'SS-001',
        highlightDefinitionId: 'HD-001',
        matchStatus: 'matched_with_highlight',
        sortOrder: 1,
      },
      {
        id: 'SI-002',
        submittalId: 'SUB-001',
        quoteLineItemId: 'LI-002',
        quoteId: 'Q-2024-001',
        fixtureType: 'F2',
        manufacturer: 'Lutron',
        catalogNumber: 'PLX-200-DIM',
        description: 'Programmable Dimmer Switch with Daylight Harvesting',
        quantity: 75,
        specSheetId: 'SS-005',
        highlightDefinitionId: 'HD-002',
        matchStatus: 'matched_with_highlight',
        sortOrder: 2,
      },
      {
        id: 'SI-003',
        submittalId: 'SUB-001',
        quoteLineItemId: 'LI-005',
        quoteId: 'Q-2024-001',
        fixtureType: 'F3',
        manufacturer: 'Acuity Brands',
        catalogNumber: 'LX-2200-REC',
        description: 'Recessed LED Downlight 6" 3000K Dimmable',
        quantity: 320,
        specSheetId: 'SS-002',
        highlightDefinitionId: 'HD-003',
        matchStatus: 'matched_with_highlight',
        sortOrder: 3,
      },
      {
        id: 'SI-004',
        submittalId: 'SUB-001',
        quoteLineItemId: 'LI-006',
        quoteId: 'Q-2024-001',
        fixtureType: 'F4',
        manufacturer: 'Acuity Brands',
        catalogNumber: 'TRK-LED-30W',
        description: 'Track Light Head LED 30W Adjustable Beam',
        quantity: 48,
        specSheetId: 'SS-003',
        highlightDefinitionId: 'HD-004',
        matchStatus: 'matched_with_highlight',
        sortOrder: 4,
      },
      {
        id: 'SI-005',
        submittalId: 'SUB-001',
        fixtureType: 'F5',
        manufacturer: 'Acuity Brands',
        catalogNumber: 'EX-200-LED',
        description: 'Emergency Exit Sign LED with Battery Backup',
        quantity: 24,
        specSheetId: 'SS-011',
        highlightDefinitionId: 'HD-005',
        matchStatus: 'matched_with_highlight',
        sortOrder: 5,
      },
    ],
    revisions: [
      {
        revisionNumber: 0,
        generatedAt: '2024-03-21T15:00:00Z',
        generatedBy: 'Sarah Chen',
        generatedPdfUrl: '/submittals/SUB-001-R0.pdf',
        generatedPdfName: 'Downtown_Medical_Center_Submittal_R0.pdf',
        generatedPdfSize: 15728640,
        outputOptions: {
          includeCoverPage: true,
          includeTransmittalPage: true,
          includeFixtureSummary: false,
          includePages: true,
          includeTypeCoverPage: false,
          showQuantities: true,
          showDescriptions: true,
          showLeadTimes: false,
          hideNotes: false,
          useCustomerLogo: false,
          printDuplex: false,
          attachments: ['specifications'],
          transmittedFor: ['approval'],
          addressedTo: [stakeholders.engineers[0]],
        },
        emailsSent: [
          {
            id: 'EMAIL-001',
            sentAt: '2024-03-21T15:30:00Z',
            sentBy: 'Sarah Chen',
            recipients: ['mwilson@wsengineering.com'],
            subject: 'Submittal - Downtown Medical Center - Rev 0',
            body: 'Please find attached the submittal package for Downtown Medical Center. Please review and provide your approval.',
            attachmentUrl: '/submittals/SUB-001-R0.pdf',
            attachmentName: 'Downtown_Medical_Center_Submittal_R0.pdf',
            attachmentSize: 15728640,
          },
        ],
        returnedPdfs: [
          {
            id: 'RET-001',
            revisionNumber: 0,
            fileName: 'Downtown_Medical_Center_Submittal_R0_Reviewed.pdf',
            fileUrl: '/submittals/returned/SUB-001-R0-reviewed.pdf',
            fileSize: 16500000,
            uploadedAt: '2024-03-24T10:00:00Z',
            uploadedBy: 'Sarah Chen',
            returnedBy: stakeholders.engineers[0],
            receivedDate: '2024-03-24',
            notes: 'Engineer review completed. Some items need revision.',
            changeAnalysis: {
              id: 'CA-001',
              analyzedAt: '2024-03-24T10:05:00Z',
              analyzedBy: 'ai',
              totalChangesDetected: 2,
              overallStatus: 'revise_and_resubmit',
              summary: '2 items need revision. F4 rejected - fixture too large for space. F2 needs different finish.',
              itemChanges: [
                {
                  id: 'IC-001',
                  itemId: 'SI-004',
                  fixtureType: 'F4',
                  catalogNumber: 'TRK-LED-30W',
                  manufacturer: 'Acuity Brands',
                  status: 'rejected',
                  notes: ['Fixture will impede on pit width', 'Choose different track head with smaller profile'],
                  pageReferences: [12],
                  resolved: true,
                  resolvedAt: '2024-03-25T09:00:00Z',
                },
                {
                  id: 'IC-002',
                  itemId: 'SI-002',
                  fixtureType: 'F2',
                  catalogNumber: 'PLX-200-DIM',
                  manufacturer: 'Lutron',
                  status: 'revise',
                  notes: ['Change finish from white to black to match wall plates'],
                  pageReferences: [8],
                  resolved: true,
                  resolvedAt: '2024-03-25T09:15:00Z',
                },
              ],
            },
          },
        ],
      },
      {
        revisionNumber: 1,
        generatedAt: '2024-03-25T14:30:00Z',
        generatedBy: 'Sarah Chen',
        generatedPdfUrl: '/submittals/SUB-001-R1.pdf',
        generatedPdfName: 'Downtown_Medical_Center_Submittal_R1.pdf',
        generatedPdfSize: 16252928,
        outputOptions: {
          includeCoverPage: true,
          includeTransmittalPage: true,
          includeFixtureSummary: false,
          includePages: true,
          includeTypeCoverPage: false,
          showQuantities: true,
          showDescriptions: true,
          showLeadTimes: true,
          hideNotes: false,
          useCustomerLogo: false,
          printDuplex: false,
          attachments: ['specifications', 'drawings'],
          transmittedFor: ['resubmit_for_approval'],
          addressedTo: [stakeholders.engineers[0], stakeholders.architects[0]],
        },
        emailsSent: [
          {
            id: 'EMAIL-002',
            sentAt: '2024-03-25T14:45:00Z',
            sentBy: 'Sarah Chen',
            recipients: ['mwilson@wsengineering.com', 'jtaylor@arcdesign.com'],
            subject: 'Resubmittal - Downtown Medical Center - Rev 1',
            body: 'Please find attached the revised submittal package. Changes have been made per your comments on Rev 0.',
            attachmentUrl: '/submittals/SUB-001-R1.pdf',
            attachmentName: 'Downtown_Medical_Center_Submittal_R1.pdf',
            attachmentSize: 16252928,
          },
        ],
        returnedPdfs: [],
      },
    ],
    createdBy: 'Sarah Chen',
    updatedBy: 'Sarah Chen',
    config: defaultSubmittalConfig,
    tags: ['Healthcare', 'Priority'],
  },

  // Submittal 2: TechCorp HQ (from Q-2024-002) - Approved
  {
    id: 'SUB-002',
    jobId: 'J-002',
    jobName: 'TechCorp HQ Expansion',
    jobLocation: '1200 Innovation Drive, San Jose, CA 95110',
    quoteIds: ['Q-2024-002'],
    customers: [stakeholders.customers[1]],
    engineers: [stakeholders.engineers[1]],
    architects: [stakeholders.architects[1]],
    bidDate: '2024-04-01',
    submittalDate: '2024-03-10',
    createdAt: '2024-03-08T09:00:00Z',
    updatedAt: '2024-03-18T11:00:00Z',
    status: 'approved',
    currentRevision: 2,
    items: [
      {
        id: 'SI-006',
        submittalId: 'SUB-002',
        fixtureType: 'A',
        manufacturer: 'Lutron',
        catalogNumber: 'GRAFIK-EYE-QS',
        description: 'GRAFIK Eye QS Wireless Control Unit',
        quantity: 12,
        specSheetId: 'SS-006',
        matchStatus: 'matched_no_highlight',
        sortOrder: 1,
      },
      {
        id: 'SI-007',
        submittalId: 'SUB-002',
        fixtureType: 'B',
        manufacturer: 'Philips',
        catalogNumber: 'PEND-MOD-18',
        description: 'Modern Pendant Light 18" Decorative LED',
        quantity: 24,
        specSheetId: 'SS-008',
        matchStatus: 'matched_no_highlight',
        sortOrder: 2,
      },
      {
        id: 'SI-008',
        submittalId: 'SUB-002',
        fixtureType: 'C',
        manufacturer: 'Leviton',
        catalogNumber: 'DEC-DIM-600W',
        description: 'Decora Dimmer Switch 600W',
        quantity: 45,
        specSheetId: 'SS-007',
        matchStatus: 'matched_no_highlight',
        sortOrder: 3,
      },
    ],
    revisions: [
      {
        revisionNumber: 0,
        generatedAt: '2024-03-10T10:00:00Z',
        generatedBy: 'Marcus Chen',
        generatedPdfUrl: '/submittals/SUB-002-R0.pdf',
        generatedPdfName: 'TechCorp_HQ_Expansion_Submittal_R0.pdf',
        generatedPdfSize: 8388608,
        outputOptions: {
          includeCoverPage: true,
          includeTransmittalPage: true,
          includeFixtureSummary: false,
          includePages: true,
          includeTypeCoverPage: false,
          showQuantities: true,
          showDescriptions: true,
          showLeadTimes: false,
          hideNotes: false,
          useCustomerLogo: false,
          printDuplex: false,
          attachments: ['specifications'],
          transmittedFor: ['approval'],
          addressedTo: [stakeholders.engineers[1]],
        },
        emailsSent: [
          {
            id: 'EMAIL-003',
            sentAt: '2024-03-10T10:30:00Z',
            sentBy: 'Marcus Chen',
            recipients: ['dpark@parkeng.com'],
            subject: 'Submittal - TechCorp HQ Expansion - Rev 0',
            body: 'Please find attached the submittal package for TechCorp HQ Expansion.',
            attachmentUrl: '/submittals/SUB-002-R0.pdf',
            attachmentName: 'TechCorp_HQ_Expansion_Submittal_R0.pdf',
            attachmentSize: 8388608,
          },
        ],
        returnedPdfs: [
          {
            id: 'RP-001',
            revisionNumber: 0,
            fileName: 'TechCorp_HQ_Expansion_Submittal_R0_Reviewed.pdf',
            fileUrl: '/submittals/returned/SUB-002-R0-marked.pdf',
            fileSize: 9437184,
            uploadedAt: '2024-03-12T16:00:00Z',
            uploadedBy: 'Marcus Chen',
            returnedBy: stakeholders.engineers[1],
            receivedDate: '2024-03-12',
            notes: 'Requested changes to pendant mounting height specifications',
            changeAnalysis: {
              id: 'CA-002',
              analyzedAt: '2024-03-12T16:10:00Z',
              analyzedBy: 'ai',
              totalChangesDetected: 1,
              overallStatus: 'approved_as_noted',
              summary: 'Pendant mounting height needs adjustment. Otherwise approved.',
              itemChanges: [
                {
                  id: 'IC-003',
                  itemId: 'SI-007',
                  fixtureType: 'B',
                  catalogNumber: 'PEND-MOD-18',
                  manufacturer: 'Philips',
                  status: 'approved_as_noted',
                  notes: ['Adjust mounting height from 36" to 42" above desk surface', 'Verify cord length is sufficient'],
                  pageReferences: [4, 5],
                  resolved: true,
                  resolvedAt: '2024-03-13T09:00:00Z',
                },
              ],
            },
          },
        ],
      },
      {
        revisionNumber: 1,
        generatedAt: '2024-03-14T11:00:00Z',
        generatedBy: 'Marcus Chen',
        generatedPdfUrl: '/submittals/SUB-002-R1.pdf',
        generatedPdfName: 'TechCorp_HQ_Expansion_Submittal_R1.pdf',
        generatedPdfSize: 8650752,
        outputOptions: {
          includeCoverPage: true,
          includeTransmittalPage: true,
          includeFixtureSummary: false,
          includePages: true,
          includeTypeCoverPage: false,
          showQuantities: true,
          showDescriptions: true,
          showLeadTimes: true,
          hideNotes: false,
          useCustomerLogo: false,
          printDuplex: false,
          attachments: ['specifications'],
          transmittedFor: ['resubmit_for_approval'],
          addressedTo: [stakeholders.engineers[1]],
        },
        emailsSent: [
          {
            id: 'EMAIL-004',
            sentAt: '2024-03-14T11:15:00Z',
            sentBy: 'Marcus Chen',
            recipients: ['dpark@parkeng.com'],
            subject: 'Resubmittal - TechCorp HQ Expansion - Rev 1',
            body: 'Please find attached the revised submittal. Mounting height updated per your comments.',
            attachmentUrl: '/submittals/SUB-002-R1.pdf',
            attachmentName: 'TechCorp_HQ_Expansion_Submittal_R1.pdf',
            attachmentSize: 8650752,
          },
        ],
        returnedPdfs: [
          {
            id: 'RP-002',
            revisionNumber: 1,
            fileName: 'TechCorp_HQ_Expansion_Submittal_R1_Approved.pdf',
            fileUrl: '/submittals/returned/SUB-002-R1-approved.pdf',
            fileSize: 8800000,
            uploadedAt: '2024-03-16T14:00:00Z',
            uploadedBy: 'Marcus Chen',
            returnedBy: stakeholders.engineers[1],
            receivedDate: '2024-03-16',
            notes: 'Approved - ready for record submittal',
            changeAnalysis: {
              id: 'CA-003',
              analyzedAt: '2024-03-16T14:05:00Z',
              analyzedBy: 'ai',
              totalChangesDetected: 0,
              overallStatus: 'approved',
              summary: 'All items approved. No changes required.',
              itemChanges: [],
            },
          },
        ],
      },
      {
        revisionNumber: 2,
        generatedAt: '2024-03-18T11:00:00Z',
        generatedBy: 'Marcus Chen',
        generatedPdfUrl: '/submittals/SUB-002-R2.pdf',
        generatedPdfName: 'TechCorp_HQ_Expansion_Submittal_R2_Record.pdf',
        generatedPdfSize: 8912896,
        outputOptions: {
          includeCoverPage: true,
          includeTransmittalPage: true,
          includeFixtureSummary: false,
          includePages: true,
          includeTypeCoverPage: false,
          showQuantities: true,
          showDescriptions: true,
          showLeadTimes: true,
          hideNotes: false,
          useCustomerLogo: false,
          printDuplex: false,
          attachments: ['specifications'],
          transmittedFor: ['record'],
          addressedTo: [stakeholders.engineers[1], stakeholders.architects[1]],
        },
        emailsSent: [
          {
            id: 'EMAIL-005',
            sentAt: '2024-03-18T11:15:00Z',
            sentBy: 'Marcus Chen',
            recipients: ['dpark@parkeng.com', 'klee@modernarch.com'],
            subject: 'Record Submittal - TechCorp HQ Expansion - Rev 2',
            body: 'Please find attached the final record submittal for TechCorp HQ Expansion.',
            attachmentUrl: '/submittals/SUB-002-R2.pdf',
            attachmentName: 'TechCorp_HQ_Expansion_Submittal_R2_Record.pdf',
            attachmentSize: 8912896,
          },
        ],
        returnedPdfs: [],
      },
    ],
    createdBy: 'Marcus Chen',
    updatedBy: 'Marcus Chen',
    config: defaultSubmittalConfig,
    tags: ['Office', 'Controls'],
  },

  // Submittal 3: University Lab - Draft (from Q-2024-003)
  {
    id: 'SUB-003',
    jobId: 'J-005',
    jobName: 'University Lab Building',
    jobLocation: '500 University Ave, Palo Alto, CA 94301',
    quoteIds: ['Q-2024-003'],
    customers: [],
    engineers: [],
    architects: [],
    bidDate: '2024-05-01',
    submittalDate: '2024-04-01',
    createdAt: '2024-03-22T14:00:00Z',
    updatedAt: '2024-03-22T14:00:00Z',
    status: 'draft',
    currentRevision: 0,
    items: [
      {
        id: 'SI-009',
        submittalId: 'SUB-003',
        fixtureType: 'L1',
        manufacturer: 'Waldmann',
        catalogNumber: 'WLD-TASK-01',
        description: 'Task Light LED Adjustable Arm',
        quantity: 60,
        specSheetId: 'SS-009',
        matchStatus: 'matched_no_highlight',
        sortOrder: 1,
      },
      {
        id: 'SI-010',
        submittalId: 'SUB-003',
        fixtureType: 'L2',
        manufacturer: 'Acuity Brands',
        catalogNumber: 'LX-4500-LED',
        description: 'Linear LED Fixture 4ft 5000K with Integrated Driver',
        quantity: 80,
        specSheetId: 'SS-001',
        highlightDefinitionId: 'HD-001',
        matchStatus: 'matched_with_highlight',
        sortOrder: 2,
      },
      {
        id: 'SI-011',
        submittalId: 'SUB-003',
        fixtureType: 'L3',
        manufacturer: 'Unknown',
        catalogNumber: 'SPEC-HOOD-24',
        description: 'Fume Hood Light Fixture 24"',
        matchStatus: 'no_match',
        sortOrder: 3,
      },
    ],
    revisions: [],
    createdBy: 'David Torres',
    updatedBy: 'David Torres',
    config: defaultSubmittalConfig,
    tags: ['Education', 'Lab Systems'],
  },

  // Submittal 4: From scratch (no quote)
  {
    id: 'SUB-004',
    jobId: 'J-004',
    jobName: 'Harbor View Apartments',
    jobLocation: '888 Harbor Blvd, Long Beach, CA 90802',
    quoteIds: [],
    customers: [stakeholders.customers[2]],
    engineers: [],
    architects: [stakeholders.architects[1]],
    bidDate: '2024-03-01',
    submittalDate: '2024-02-20',
    createdAt: '2024-02-18T10:00:00Z',
    updatedAt: '2024-02-28T16:00:00Z',
    status: 'approved_as_noted',
    currentRevision: 1,
    items: [
      {
        id: 'SI-012',
        submittalId: 'SUB-004',
        fixtureType: 'R1',
        manufacturer: 'Acuity Brands',
        catalogNumber: 'LX-2200-REC',
        description: 'Recessed LED Downlight 6" 3000K Dimmable',
        quantity: 450,
        specSheetId: 'SS-002',
        highlightDefinitionId: 'HD-003',
        matchStatus: 'matched_with_highlight',
        itemApprovalStatus: 'approved',
        sortOrder: 1,
      },
      {
        id: 'SI-013',
        submittalId: 'SUB-004',
        fixtureType: 'R2',
        manufacturer: 'Acuity Brands',
        catalogNumber: 'HOL-AREA-150',
        description: 'Holophane Area Light 150W LED',
        quantity: 24,
        specSheetId: 'SS-004',
        matchStatus: 'matched_no_highlight',
        itemApprovalStatus: 'approved_as_noted',
        approvalNotes: 'Use warm white (3000K) instead of specified 4000K',
        sortOrder: 2,
      },
    ],
    revisions: [
      {
        revisionNumber: 0,
        generatedAt: '2024-02-20T14:00:00Z',
        generatedBy: 'Sarah Chen',
        generatedPdfUrl: '/submittals/SUB-004-R0.pdf',
        generatedPdfName: 'Harbor_View_Apartments_Submittal_R0.pdf',
        generatedPdfSize: 6291456,
        outputOptions: {
          includeCoverPage: true,
          includeTransmittalPage: true,
          includeFixtureSummary: false,
          includePages: true,
          includeTypeCoverPage: false,
          showQuantities: true,
          showDescriptions: true,
          showLeadTimes: false,
          hideNotes: false,
          useCustomerLogo: false,
          printDuplex: false,
          attachments: ['specifications'],
          transmittedFor: ['approval'],
          addressedTo: [stakeholders.architects[1]],
        },
        emailsSent: [
          {
            id: 'EMAIL-006',
            sentAt: '2024-02-20T14:30:00Z',
            sentBy: 'Sarah Chen',
            recipients: ['klee@modernarch.com'],
            subject: 'Submittal - Harbor View Apartments - Rev 0',
            body: 'Please find attached the submittal package for Harbor View Apartments.',
            attachmentUrl: '/submittals/SUB-004-R0.pdf',
            attachmentName: 'Harbor_View_Apartments_Submittal_R0.pdf',
            attachmentSize: 6291456,
          },
        ],
        returnedPdfs: [
          {
            id: 'RP-003',
            revisionNumber: 0,
            fileName: 'Harbor_View_Apartments_Submittal_R0_Reviewed.pdf',
            fileUrl: '/submittals/returned/SUB-004-R0-architect-comments.pdf',
            fileSize: 6815744,
            uploadedAt: '2024-02-25T10:00:00Z',
            uploadedBy: 'Sarah Chen',
            returnedBy: stakeholders.architects[1],
            receivedDate: '2024-02-24',
            notes: 'Approved with note to change color temperature on exterior fixtures',
            changeAnalysis: {
              id: 'CA-004',
              analyzedAt: '2024-02-25T10:10:00Z',
              analyzedBy: 'ai',
              totalChangesDetected: 1,
              overallStatus: 'approved_as_noted',
              summary: 'Approved as noted. Change exterior fixture color temp from 4000K to 3000K.',
              itemChanges: [
                {
                  id: 'IC-004',
                  itemId: 'SI-013',
                  fixtureType: 'R2',
                  catalogNumber: 'HOL-AREA-150',
                  manufacturer: 'Acuity Brands',
                  status: 'approved_as_noted',
                  notes: ['Use warm white (3000K) instead of specified 4000K to match building aesthetic'],
                  pageReferences: [8],
                  resolved: true,
                  resolvedAt: '2024-02-26T09:00:00Z',
                },
              ],
            },
          },
        ],
      },
      {
        revisionNumber: 1,
        generatedAt: '2024-02-28T16:00:00Z',
        generatedBy: 'Sarah Chen',
        generatedPdfUrl: '/submittals/SUB-004-R1.pdf',
        generatedPdfName: 'Harbor_View_Apartments_Submittal_R1_Record.pdf',
        generatedPdfSize: 6553600,
        outputOptions: {
          includeCoverPage: true,
          includeTransmittalPage: true,
          includeFixtureSummary: false,
          includePages: true,
          includeTypeCoverPage: false,
          showQuantities: true,
          showDescriptions: true,
          showLeadTimes: false,
          hideNotes: false,
          useCustomerLogo: false,
          printDuplex: false,
          attachments: ['specifications'],
          transmittedFor: ['record'],
          addressedTo: [stakeholders.architects[1], stakeholders.customers[2]],
        },
        emailsSent: [
          {
            id: 'EMAIL-007',
            sentAt: '2024-02-28T16:15:00Z',
            sentBy: 'Sarah Chen',
            recipients: ['klee@modernarch.com', 'emily.chen@acmeconstruction.com'],
            subject: 'Record Submittal - Harbor View Apartments - Rev 1',
            body: 'Please find attached the final record submittal for Harbor View Apartments.',
            attachmentUrl: '/submittals/SUB-004-R1.pdf',
            attachmentName: 'Harbor_View_Apartments_Submittal_R1_Record.pdf',
            attachmentSize: 6553600,
          },
        ],
        returnedPdfs: [],
      },
    ],
    createdBy: 'Sarah Chen',
    updatedBy: 'Sarah Chen',
    config: defaultSubmittalConfig,
    tags: ['Residential', 'Multi-family'],
  },
];

// -----------------------------------------------------------------------------
// Helper Functions
// -----------------------------------------------------------------------------

export function getSubmittalSummaries(): SubmittalSummary[] {
  return mockSubmittals.map((s) => ({
    id: s.id,
    jobName: s.jobName,
    status: s.status,
    itemCount: s.items.length,
    currentRevision: s.currentRevision,
    submittalDate: s.submittalDate,
    updatedAt: s.updatedAt,
    customerName: s.customers[0]?.companyName,
    matchedCount: s.items.filter(
      (i) => i.matchStatus === 'matched_with_highlight' || i.matchStatus === 'matched_no_highlight'
    ).length,
    highlightedCount: s.items.filter((i) => i.matchStatus === 'matched_with_highlight').length,
  }));
}

export function getSpecSheetsByManufacturer(): Record<string, SpecSheet[]> {
  const grouped: Record<string, SpecSheet[]> = {};
  mockSpecSheets.forEach((sheet) => {
    if (!grouped[sheet.manufacturer]) {
      grouped[sheet.manufacturer] = [];
    }
    grouped[sheet.manufacturer].push(sheet);
  });
  return grouped;
}

export function getManufacturersWithSpecSheets(): string[] {
  return Array.from(new Set(mockSpecSheets.map((s) => s.manufacturer))).sort();
}

export function findHighlightDefinition(
  manufacturer: string,
  catalogNumber: string
): HighlightDefinition | undefined {
  return mockHighlightDefinitions.find(
    (h) => h.manufacturer === manufacturer && h.catalogNumber === catalogNumber
  );
}

export function findSpecSheetWithHighlight(
  manufacturer: string,
  catalogNumber: string
): { specSheet: SpecSheet; highlight: HighlightDefinition } | undefined {
  const highlight = findHighlightDefinition(manufacturer, catalogNumber);
  if (highlight) {
    const specSheet = mockSpecSheets.find((s) => s.id === highlight.specSheetId);
    if (specSheet) {
      return { specSheet, highlight };
    }
  }
  return undefined;
}

export function findSpecSheetByManufacturer(manufacturer: string): SpecSheet | undefined {
  return mockSpecSheets.find((s) => s.manufacturer === manufacturer);
}

// Status display helpers
export const submittalStatusLabels: Record<string, string> = {
  draft: 'Draft',
  for_approval: 'For Approval',
  resubmit_for_approval: 'Resubmit for Approval',
  record: 'Record',
  approved: 'Approved',
  approved_as_noted: 'Approved as Noted',
  approved_as_submitted: 'Approved as Submitted',
  rejected: 'Rejected',
};

export const submittalStatusColors: Record<string, { bg: string; text: string }> = {
  draft: { bg: 'bg-gray-100', text: 'text-gray-700' },
  for_approval: { bg: 'bg-blue-100', text: 'text-blue-700' },
  resubmit_for_approval: { bg: 'bg-yellow-100', text: 'text-yellow-700' },
  record: { bg: 'bg-purple-100', text: 'text-purple-700' },
  approved: { bg: 'bg-green-100', text: 'text-green-700' },
  approved_as_noted: { bg: 'bg-emerald-100', text: 'text-emerald-700' },
  approved_as_submitted: { bg: 'bg-green-100', text: 'text-green-700' },
  rejected: { bg: 'bg-red-100', text: 'text-red-700' },
};

export const matchStatusLabels: Record<string, string> = {
  matched_with_highlight: 'Ready',
  matched_no_highlight: 'Needs Highlight',
  no_match: 'No Spec Sheet',
};

export const matchStatusColors: Record<string, { bg: string; text: string }> = {
  matched_with_highlight: { bg: 'bg-green-100', text: 'text-green-700' },
  matched_no_highlight: { bg: 'bg-yellow-100', text: 'text-yellow-700' },
  no_match: { bg: 'bg-red-100', text: 'text-red-700' },
};

export const specSheetCategoryLabels: Record<string, string> = {
  indoor: 'Indoor',
  outdoor: 'Outdoor',
  sports_lighting: 'Sports Lighting',
  controls: 'Controls',
  emergency: 'Emergency',
  decorative: 'Decorative',
  industrial: 'Industrial',
  drives: 'Drives',
  sub_metering: 'Sub-Metering',
  cable_tray: 'Cable Tray',
  other: 'Other',
};

// Get all unique tags from spec sheets
export function getAllSpecSheetTags(): string[] {
  const tagSet = new Set<string>();
  mockSpecSheets.forEach((sheet) => {
    sheet.tags.forEach((tag) => tagSet.add(tag));
  });
  return Array.from(tagSet).sort();
}

// Get folders for a specific manufacturer
export function getFoldersForManufacturer(manufacturer: string): SpecSheetFolder[] {
  return mockSpecSheetFolders.filter((f) => f.manufacturer === manufacturer);
}

// Get child folders for a given folder
export function getChildFolders(parentId: string): SpecSheetFolder[] {
  return mockSpecSheetFolders.filter((f) => f.parentId === parentId);
}

// Get root folders (no parent) for a manufacturer
export function getRootFoldersForManufacturer(manufacturer: string): SpecSheetFolder[] {
  return mockSpecSheetFolders.filter(
    (f) => f.manufacturer === manufacturer && f.parentId === null
  );
}

// Get spec sheets in a specific folder
export function getSpecSheetsInFolder(folderId: string): SpecSheet[] {
  return mockSpecSheets.filter((s) => s.folderId === folderId);
}

// Get spec sheets with highlights
export function getSpecSheetsWithHighlights(): SpecSheet[] {
  return mockSpecSheets.filter((s) => (s.highlightCount || 0) > 0);
}

// Get spec sheets without highlights
export function getSpecSheetsWithoutHighlights(): SpecSheet[] {
  return mockSpecSheets.filter((s) => (s.highlightCount || 0) === 0);
}

// Filter spec sheets by tag
export function getSpecSheetsByTag(tag: string): SpecSheet[] {
  return mockSpecSheets.filter((s) => s.tags.includes(tag));
}
