/**
 * Mock Data for Pre-Opportunities
 */

import type { PreOpp } from './types';

// Initial pre-opportunities data
export const INITIAL_PRE_OPPS: PreOpp[] = [
  {
    id: 'PO-001',
    name: 'Downtown Plaza LED Upgrade',
    job: 'J-001',
    stage: 'Qualified',
    value: '$45,000',
    soldTo: 'Turner Construction',
    manufacturer: 'Acuity Brands',
    dateCreated: '2024-01-15',
    expirationDate: '2024-04-15',
    owner: 'Sarah Johnson',
    tags: ['Lighting', 'LED'],
  },
  {
    id: 'PO-002',
    name: 'TechCorp Emergency Lighting',
    job: 'J-002',
    stage: 'Negotiation',
    value: '$28,500',
    soldTo: 'Hensel Phelps',
    manufacturer: 'Eaton',
    dateCreated: '2024-01-20',
    expirationDate: '2024-03-20',
    owner: 'Marcus Chen',
    tags: ['Emergency', 'Controls'],
  },
  {
    id: 'PO-003',
    name: 'Medical Center Backup Power',
    job: 'J-003',
    stage: 'Follow-up',
    value: '$95,000',
    soldTo: 'McCarthy Building',
    manufacturer: 'Schneider Electric',
    dateCreated: '2024-02-01',
    expirationDate: '2024-05-01',
    owner: 'Sarah Johnson',
    tags: ['Critical', 'Power'],
  },
  {
    id: 'PO-004',
    name: 'Westside Mall EV Chargers',
    job: 'J-006',
    stage: 'Waiting on Factory',
    value: '$125,000',
    soldTo: 'Gilbane Building',
    manufacturer: 'ChargePoint',
    dateCreated: '2024-02-10',
    expirationDate: '2024-06-10',
    owner: 'David Torres',
    tags: ['EV', 'Infrastructure'],
  },
  {
    id: 'PO-005',
    name: 'Harbor Apartments Smart Controls',
    job: 'J-004',
    stage: 'Converted',
    value: '$62,000',
    soldTo: 'Turner Construction',
    manufacturer: 'Lutron',
    dateCreated: '2024-01-05',
    expirationDate: '2024-03-05',
    owner: 'Marcus Chen',
    tags: ['Smart Home', 'Controls'],
  },
  {
    id: 'PO-006',
    name: 'University Lab Specialty Lighting',
    job: 'J-005',
    stage: 'Negotiation',
    value: '$78,500',
    soldTo: 'Hensel Phelps',
    manufacturer: 'Signify',
    dateCreated: '2024-02-15',
    expirationDate: '2024-05-15',
    owner: 'David Torres',
    tags: ['Lab Systems', 'Specialty'],
  },
  {
    id: 'PO-007',
    name: 'City Center Office Tower Fixtures',
    job: 'J-007',
    stage: 'Qualified',
    value: '$52,000',
    soldTo: 'Turner Construction',
    manufacturer: 'Cooper Lighting',
    dateCreated: '2024-01-25',
    expirationDate: '2024-04-25',
    owner: 'Marcus Chen',
    tags: ['High-rise', 'Commercial'],
  },
  {
    id: 'PO-008',
    name: 'Airport Terminal Exit Signs',
    job: 'J-008',
    stage: 'Qualified',
    value: '$38,000',
    soldTo: 'Hensel Phelps',
    manufacturer: 'Philips',
    dateCreated: '2024-02-20',
    expirationDate: '2024-06-20',
    owner: 'David Torres',
    tags: ['Infrastructure', 'Safety'],
  },
];
