query GetFileValidationIssues {
  fileValidationIssues {
    blocking {
      count
      items {
        id
        rowNumber
        title
        columnName
        fileId
        fileName
      }
    }
    warning {
      count
      items {
        id
        rowNumber
        title
        columnName
        fileId
        fileName
      }
    }
    fyi {
      count
      items {
        id
        rowNumber
        title
        columnName
        fileId
        fileName
      }
    }
  }
}
