import type { SavedView, ColumnKey } from '../types';

export const defaultSavedViews: SavedView[] = [
  {
    id: 'default',
    name: 'Default',
    columns: [
      'partNumber',
      'description',
      'manufacturer',
      'quantity',
      'unitPrice',
      'sellTotal',
      'l1',
      'l2',
      'specSheet',
    ] as ColumnKey[],
  },
  {
    id: 'compact',
    name: 'Compact',
    columns: [
      'partNumber',
      'description',
      'quantity',
      'unitPrice',
      'sellTotal',
    ] as ColumnKey[],
  },
  {
    id: 'earnings',
    name: 'Earnings View',
    columns: [
      'partNumber',
      'description',
      'manufacturer',
      'quantity',
      'unitPrice',
      'sellTotal',
      'overage',
      'overageAmt',
      'commRate',
      'baseComm',
      'overageShare',
      'overageComm',
      'totalEarn',
      'effRate',
      'trend',
    ] as ColumnKey[],
  },
  {
    id: 'pricing',
    name: 'Full Pricing',
    columns: [
      'partNumber',
      'description',
      'manufacturer',
      'quantity',
      'unitPrice',
      'sellTotal',
      'l1',
      'l2',
      'l3',
      'overage',
      'trend',
    ] as ColumnKey[],
  },
  {
    id: 'approval',
    name: 'Approval Focus',
    columns: [
      'partNumber',
      'description',
      'manufacturer',
      'quantity',
      'unitPrice',
      'endUser',
      'specSheet',
    ] as ColumnKey[],
  },
];
