// ============================================================================
// Flow Submittals - Type Definitions
// ============================================================================

// -----------------------------------------------------------------------------
// Enums & Constants
// -----------------------------------------------------------------------------

export type SubmittalStatus =
  | 'draft'
  | 'for_approval'
  | 'resubmit_for_approval'
  | 'record'
  | 'approved'
  | 'approved_as_noted'
  | 'approved_as_submitted'
  | 'rejected';

export type TransmittalPurpose =
  | 'prior_approval'
  | 'approval'
  | 'approval_as_submitted'
  | 'approval_as_noted'
  | 'resubmit_for_approval'
  | 'record'
  | 'corrections'
  | 'review_and_comment'
  | 'for_your_use'
  | 'bids_due_on';

export type TransmittalAttachment =
  | 'drawings'
  | 'specifications'
  | 'prints'
  | 'information'
  | 'other';

export type ItemApprovalStatus =
  | 'pending'
  | 'approved'
  | 'approved_as_noted'
  | 'rejected'
  | 'revise_and_resubmit';

export type SpecSheetMatchStatus =
  | 'matched_with_highlight'
  | 'matched_no_highlight'
  | 'no_match';

export type HighlightShape =
  | 'rectangle'
  | 'oval'
  | 'highlight'
  | 'arrow'
  | 'text'
  | 'underline';

export type SpecSheetCategory =
  | 'indoor'
  | 'outdoor'
  | 'sports_lighting'
  | 'controls'
  | 'emergency'
  | 'decorative'
  | 'industrial'
  | 'drives'
  | 'sub_metering'
  | 'cable_tray'
  | 'other';

export type UploadSource = 'file' | 'url';

// -----------------------------------------------------------------------------
// Highlight Definition Types
// -----------------------------------------------------------------------------

export interface HighlightRegion {
  id: string;
  pageNumber: number;
  // Coordinates as percentages (0-100) for zoom independence
  x: number;
  y: number;
  width: number;
  height: number;
  shape: HighlightShape;
  color: string; // hex color
  strokeWidth?: number;
  annotation?: string; // text content for text boxes
  rotation?: number; // for arrows
  tags?: string[]; // user-defined tags for categorization
}

export interface HighlightDefinition {
  id: string;
  specSheetId: string;
  catalogNumber: string;
  manufacturer: string;
  regions: HighlightRegion[];
  createdAt: string;
  createdBy: string;
  updatedAt: string;
  updatedBy: string;
}

// -----------------------------------------------------------------------------
// Spec Sheet Types
// -----------------------------------------------------------------------------

export interface SpecSheetFolder {
  id: string;
  name: string;
  parentId: string | null; // null for root folders
  manufacturer?: string; // If folder is under a manufacturer
  isAutoGenerated: boolean; // true for system-created folders
  createdAt: string;
  createdBy: string;
  specSheetCount?: number; // Number of spec sheets in this folder (from API)
  folderPath?: string; // Full folder path (e.g., "F1/F2")
}

export interface SpecSheet {
  id: string;
  factoryId?: string; // Factory ID from API (used to resolve manufacturer name)
  manufacturer: string;
  fileName: string;
  displayName: string; // User-friendly name (can override fileName)
  categories: SpecSheetCategory[];
  tags: string[]; // User-defined tags for filtering
  folderId?: string; // Optional folder assignment
  folderPath?: string; // Folder path from API (e.g., "F1/F2")
  uploadSource: UploadSource;
  sourceUrl?: string; // Original URL if uploaded from URL
  fileUrl: string; // Stored file location
  fileSize: number; // bytes
  pageCount: number;
  uploadedAt: string;
  uploadedBy: string;
  updatedAt?: string;
  needsReview: boolean; // Flag for stale sheets
  usageCount: number; // How many times used in submittals
  // Computed/joined data
  highlightCount?: number; // Number of highlight definitions for this sheet
}

// -----------------------------------------------------------------------------
// Submittal Item Types
// -----------------------------------------------------------------------------

export interface SubmittalItem {
  id: string;
  submittalId: string;
  // Reference to quote line item (if created from quote)
  quoteLineItemId?: string;
  quoteId?: string;
  // Item details
  fixtureType: string; // e.g., "F1", "F2", "A", "B"
  manufacturer: string;
  catalogNumber: string;
  description: string;
  quantity?: number; // Optional, user can toggle visibility
  // Spec sheet attachment
  specSheetId?: string;
  specSheetPageRange?: { start: number; end: number }; // If only using certain pages
  highlightDefinitionId?: string;
  // Nested objects from API
  specSheet?: SpecSheet; // Populated from GraphQL response
  highlightVersion?: HighlightDefinition; // Populated from GraphQL response
  // Status
  matchStatus: SpecSheetMatchStatus;
  itemApprovalStatus?: ItemApprovalStatus;
  approvalNotes?: string;
  // Ordering
  sortOrder: number;
}

// -----------------------------------------------------------------------------
// Stakeholder Types
// -----------------------------------------------------------------------------

export interface SubmittalStakeholder {
  contactId: string;
  contactName: string;
  companyName?: string;
  email?: string;
  role: 'customer' | 'engineer' | 'architect' | 'gc' | 'ec' | 'other';
}

// -----------------------------------------------------------------------------
// Revision Types
// -----------------------------------------------------------------------------

export type ItemChangeStatus = 'approved' | 'approved_as_noted' | 'revise' | 'rejected';

export type OverallChangeStatus = 'approved' | 'approved_as_noted' | 'revise_and_resubmit' | 'rejected';

export interface ItemChange {
  id: string;
  itemId: string;
  fixtureType: string;
  catalogNumber: string;
  manufacturer: string;
  status: ItemChangeStatus;
  notes: string[];
  pageReferences?: number[];
  resolved?: boolean;
  resolvedAt?: string;
}

export interface ChangeAnalysis {
  id: string;
  analyzedAt: string;
  analyzedBy: 'ai' | 'manual';
  totalChangesDetected: number;
  itemChanges: ItemChange[];
  overallStatus: OverallChangeStatus;
  summary?: string;
}

export interface ReturnedPdf {
  id: string;
  revisionNumber: number;
  fileName: string;
  fileUrl: string;
  fileSize: number;
  uploadedAt: string;
  uploadedBy: string;
  returnedBy: SubmittalStakeholder;
  receivedDate: string;
  notes?: string;
  // Change analysis results
  changeAnalysis?: ChangeAnalysis;
}

export interface EmailSendRecord {
  id: string;
  sentAt: string;
  sentBy: string;
  recipients: string[];
  subject: string;
  body?: string;
  attachmentUrl: string;
  attachmentName: string;
  attachmentSize: number;
}

export interface SubmittalRevision {
  id?: string; // UUID from backend
  revisionNumber: number;
  generatedAt: string;
  generatedBy: string;
  generatedPdfUrl?: string;
  generatedPdfName?: string;
  generatedPdfSize?: number;
  // Output options used for this revision
  outputOptions: SubmittalOutputOptions;
  // Email send history for this revision
  emailsSent: EmailSendRecord[];
  // Returned PDFs for this revision
  returnedPdfs: ReturnedPdf[];
}

// -----------------------------------------------------------------------------
// Output Options Types
// -----------------------------------------------------------------------------

export interface SubmittalOutputOptions {
  includeCoverPage: boolean;
  includeTransmittalPage: boolean;
  includeFixtureSummary: boolean;
  includePages: boolean;
  includeTypeCoverPage: boolean;
  showQuantities: boolean;
  showDescriptions: boolean;
  showLeadTimes: boolean;
  hideNotes: boolean;
  useCustomerLogo: boolean;
  printDuplex: boolean;
  // Transmittal options
  attachments: TransmittalAttachment[];
  transmittedFor: TransmittalPurpose[];
  // Recipients
  addressedTo: SubmittalStakeholder[];
  // Item selection (if subset)
  selectedItemIds?: string[]; // If undefined, include all
}

// -----------------------------------------------------------------------------
// Submittal Configuration Options
// -----------------------------------------------------------------------------

export interface SubmittalConfig {
  // Include options
  includeLamps: boolean;
  includeAccessories: boolean;
  includeCQ: boolean; // Customer Quote items
  includeFromOrders: boolean;
  // Rollup options
  rollUpKits: boolean;
  rollUpAccessories: boolean;
  // Filter options
  includeZeroQuantityItems: boolean;
  // Display options
  dropDescriptions: boolean;
  dropLineNotes: boolean;
}

export const defaultSubmittalConfig: SubmittalConfig = {
  includeLamps: false,
  includeAccessories: false,
  includeCQ: false,
  includeFromOrders: false,
  rollUpKits: false,
  rollUpAccessories: true,
  includeZeroQuantityItems: true,
  dropDescriptions: false,
  dropLineNotes: true,
};

// -----------------------------------------------------------------------------
// Main Submittal Type
// -----------------------------------------------------------------------------

export interface Submittal {
  id: string;
  // Project/Job reference
  jobId?: string;
  jobName: string;
  jobLocation?: string;
  // Quote references (can be multiple)
  quoteIds: string[];
  // Stakeholders
  customers: SubmittalStakeholder[];
  engineers: SubmittalStakeholder[];
  architects: SubmittalStakeholder[];
  // Dates
  bidDate?: string;
  submittalDate: string;
  createdAt: string;
  updatedAt: string;
  // Status
  status: SubmittalStatus;
  currentRevision: number;
  // Items
  items: SubmittalItem[];
  // Revisions history
  revisions: SubmittalRevision[];
  // Configuration options
  config: SubmittalConfig;
  // Metadata
  createdBy: string;
  updatedBy: string;
  // Tags for filtering/organization
  tags?: string[];
}

// -----------------------------------------------------------------------------
// Helper Types for UI
// -----------------------------------------------------------------------------

export interface SubmittalSummary {
  id: string;
  jobName: string;
  status: SubmittalStatus;
  itemCount: number;
  currentRevision: number;
  submittalDate: string;
  updatedAt: string;
  customerName?: string;
  matchedCount: number; // Items with spec sheets attached
  highlightedCount: number; // Items with highlights
}

export interface SpecSheetWithHighlights extends SpecSheet {
  highlights: HighlightDefinition[];
}

export interface SubmittalItemWithDetails extends SubmittalItem {
  specSheet?: SpecSheet;
  highlightDefinition?: HighlightDefinition;
}

// -----------------------------------------------------------------------------
// Form/Input Types
// -----------------------------------------------------------------------------

export interface CreateSubmittalInput {
  jobId?: string;
  jobName: string;
  jobLocation?: string;
  quoteIds?: string[];
  bidDate?: string;
  submittalDate?: string;
  customers?: SubmittalStakeholder[];
  engineers?: SubmittalStakeholder[];
  architects?: SubmittalStakeholder[];
}

export interface CreateSubmittalFromQuoteInput {
  quoteId: string;
  selectedLineItemIds: string[];
}

export interface CreateSubmittalItemInput {
  fixtureType: string;
  manufacturer: string;
  catalogNumber: string;
  description: string;
  quantity?: number;
}

export interface CreateSpecSheetInput {
  manufacturer: string;
  displayName?: string;
  categories: SpecSheetCategory[];
  uploadSource: UploadSource;
  sourceUrl?: string;
  file?: File;
}

export interface CreateHighlightInput {
  specSheetId: string;
  catalogNumber: string;
  manufacturer: string;
  regions: Omit<HighlightRegion, 'id'>[];
}

// -----------------------------------------------------------------------------
// Filter Types
// -----------------------------------------------------------------------------

export interface SubmittalFilters {
  status?: SubmittalStatus[];
  jobId?: string;
  customerId?: string;
  dateRange?: { start: string; end: string };
  searchQuery?: string;
}

export interface SpecSheetFilters {
  manufacturer?: string;
  categories?: SpecSheetCategory[];
  tags?: string[];
  hasHighlights?: boolean; // true = only with highlights, false = only without
  needsReview?: boolean;
  folderId?: string;
  searchQuery?: string;
}
