/**
 * Folder utility functions for spec sheets
 */

import type { SpecSheetFolder } from '../../../lib/types/submittals';
import type { FolderResponse } from '../../lib/graphql/spec-sheets';

/**
 * Build folder path from hierarchy (for display purposes)
 */
export function buildFolderPath(folder: FolderResponse, allFolders: FolderResponse[]): string {
  const parts: string[] = [folder.name];
  let currentFolder: FolderResponse | undefined = folder;

  while (currentFolder?.parentId) {
    const parent = allFolders.find(f => f.id === currentFolder!.parentId);
    if (parent) {
      parts.unshift(parent.name);
      currentFolder = parent;
    } else {
      break;
    }
  }

  return parts.join('/');
}

/**
 * Convert API folders to SpecSheetFolder array with proper parent relationships
 */
export function convertToSpecSheetFolders(
  apiFolders: FolderResponse[],
  manufacturerName: string
): SpecSheetFolder[] {
  return apiFolders.map(apiFolder => ({
    id: apiFolder.id,
    name: apiFolder.name,
    parentId: apiFolder.parentId,
    manufacturer: manufacturerName,
    isAutoGenerated: false,
    createdAt: apiFolder.createdAt || '',
    createdBy: 'System',
    specSheetCount: apiFolder.specSheetCount,
    // Build folderPath from hierarchy since backend uses parent_id
    folderPath: buildFolderPath(apiFolder, apiFolders),
  }));
}
