import { useState, useMemo, useRef, useEffect } from 'react';
import {
  useFoldersByFactory,
  useCreateFolder,
  useRenameFolder,
  useDeleteFolder,
} from '../api/useSpecSheetsApi';
import type { SpecSheetFolder } from '../../../lib/types/submittals';
import { fetchFoldersByFactory as fetchFoldersApi, type FolderResponse } from '../../lib/graphql/spec-sheets';
import { showConfirmToast, showSuccessToast, showErrorToast } from '../../lib/toast';

interface Manufacturer {
  id: string;
  name: string;
}

interface UseSpecSheetsFoldersParams {
  selectedManufacturerId: string | null;
  manufacturers: Manufacturer[];
}

export function useSpecSheetsFolders({
  selectedManufacturerId,
  manufacturers,
}: UseSpecSheetsFoldersParams) {
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set());
  const [selectedFolderId, setSelectedFolderId] = useState<string | null>(null);
  const [allManufacturerFolders, setAllManufacturerFolders] = useState<Record<string, FolderResponse[]>>({});
  const [isLoadingAllFolders, setIsLoadingAllFolders] = useState(false);
  const hasLoadedFoldersRef = useRef(false);

  const [contextMenu, setContextMenu] = useState<{ folder: SpecSheetFolder; position: { x: number; y: number } } | null>(null);
  const [editingFolderId, setEditingFolderId] = useState<string | null>(null);
  const [editingFolderName, setEditingFolderName] = useState('');
  const [showAddFolderModal, setShowAddFolderModal] = useState(false);
  const [newFolderParentId, setNewFolderParentId] = useState<string | null>(null);
  const [newFolderManufacturer, setNewFolderManufacturer] = useState<string>('');
  const [newFolderManufacturerId, setNewFolderManufacturerId] = useState<string>('');
  const [newFolderName, setNewFolderName] = useState('');
  const [draggedFolderId, setDraggedFolderId] = useState<string | null>(null);
  const [dragOverFolderId, setDragOverFolderId] = useState<string | null>(null);
  const [folderError, setFolderError] = useState<string | null>(null);
  const [expandedManufacturers, setExpandedManufacturers] = useState<Set<string>>(new Set());

  const { data: foldersData, isLoading: isLoadingFolders } = useFoldersByFactory(selectedManufacturerId);

  const createFolderMutation = useCreateFolder();
  const renameFolderMutation = useRenameFolder();
  const deleteFolderMutation = useDeleteFolder();

  const isSavingFolder = renameFolderMutation.isPending || deleteFolderMutation.isPending;
  const isCreatingFolder = createFolderMutation.isPending;

  const loadAllManufacturerFolders = async (force = false) => {
    if (!manufacturers || manufacturers.length === 0) return;
    if (isLoadingAllFolders) return;
    if (hasLoadedFoldersRef.current && !force) return;

    setIsLoadingAllFolders(true);
    try {
      const foldersMap: Record<string, FolderResponse[]> = {};
      await Promise.all(
        manufacturers.map(async (m) => {
          try {
            const folders = await fetchFoldersApi(m.id);
            foldersMap[m.id] = folders;
          } catch (error) {
            console.error(`Failed to fetch folders for manufacturer ${m.id}:`, error);
            foldersMap[m.id] = [];
          }
        })
      );
      setAllManufacturerFolders(foldersMap);
      hasLoadedFoldersRef.current = true;
    } finally {
      setIsLoadingAllFolders(false);
    }
  };

  useEffect(() => {
    if (manufacturers && manufacturers.length > 0 && !hasLoadedFoldersRef.current) {
      loadAllManufacturerFolders();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [manufacturers]);

  const findManufacturerIdByName = (name: string): string | null => {
    const found = manufacturers.find(m => m.name === name);
    return found?.id || null;
  };

  const folders: SpecSheetFolder[] = useMemo(() => {
    if (!foldersData) return [];
    const selectedMfr = manufacturers.find(m => m.id === selectedManufacturerId);
    const manufacturerName = selectedMfr?.name || '';
    const folderMap = new Map<string, SpecSheetFolder>();

    for (const apiFolder of foldersData) {
      const parts = apiFolder.folderPath.split('/').filter(Boolean);
      const folderName = parts[parts.length - 1] || apiFolder.folderPath;
      folderMap.set(apiFolder.folderPath, {
        id: apiFolder.id,
        name: folderName,
        parentId: null,
        manufacturer: manufacturerName,
        isAutoGenerated: false,
        createdAt: apiFolder.createdAt || '',
        createdBy: 'System',
        specSheetCount: apiFolder.specSheetCount,
        folderPath: apiFolder.folderPath,
      });
    }

    for (const apiFolder of foldersData) {
      const parts = apiFolder.folderPath.split('/').filter(Boolean);
      if (parts.length > 1) {
        const parentPath = parts.slice(0, -1).join('/');
        const parentFolder = foldersData.find(f => f.folderPath === parentPath);
        if (parentFolder) {
          const folder = folderMap.get(apiFolder.folderPath);
          if (folder) folder.parentId = parentFolder.id;
        }
      }
    }
    return Array.from(folderMap.values());
  }, [foldersData, selectedManufacturerId, manufacturers]);

  const getFolderPath = (folderId: string): string | null => {
    if (!foldersData) return null;
    const folder = foldersData.find(f => f.id === folderId);
    return folder?.folderPath || null;
  };

  const handleFolderContextMenu = (e: React.MouseEvent, folder: SpecSheetFolder) => {
    e.preventDefault();
    e.stopPropagation();
    setContextMenu({ folder, position: { x: e.clientX, y: e.clientY } });
  };

  const handleRenameFolder = (folder: SpecSheetFolder) => {
    setEditingFolderId(folder.id);
    setEditingFolderName(folder.name);
  };

  const handleSaveRename = async () => {
    if (!editingFolderId || !editingFolderName.trim() || !selectedManufacturerId) {
      setEditingFolderId(null);
      setEditingFolderName('');
      return;
    }
    const folderPath = getFolderPath(editingFolderId);
    if (!folderPath) { setEditingFolderId(null); setEditingFolderName(''); return; }
    setFolderError(null);
    try {
      await renameFolderMutation.mutateAsync({ factoryId: selectedManufacturerId, folderPath, newName: editingFolderName.trim() });
      loadAllManufacturerFolders(true);
    } catch (error) {
      setFolderError(error instanceof Error ? error.message : 'Failed to rename folder');
    } finally {
      setEditingFolderId(null);
      setEditingFolderName('');
    }
  };

  const handleDeleteFolder = async (folder: SpecSheetFolder) => {
    if (!selectedManufacturerId) return;
    const folderPath = folder.folderPath || getFolderPath(folder.id);
    if (!folderPath) return;

    // Check for subfolders first (before spec sheets, since specSheetCount may include nested counts)
    // Use the folders array which checks by parentId relationship
    const hasSubfolders = folders.some(f => f.parentId === folder.id);

    if (hasSubfolders) {
      showErrorToast('Cannot delete folder', {
        description: 'This folder contains subfolders. Delete them first.',
      });
      return;
    }

    // Check if folder has direct spec sheets (only relevant after confirming no subfolders)
    if ((folder.specSheetCount || 0) > 0) {
      showErrorToast('Cannot delete folder', {
        description: 'This folder contains spec sheets. Move or delete them first.',
      });
      return;
    }

    const confirmed = await showConfirmToast(`Delete folder "${folder.name}"?`, {
      confirmLabel: 'Delete',
    });

    if (confirmed) {
      setFolderError(null);
      try {
        await deleteFolderMutation.mutateAsync({ factoryId: selectedManufacturerId, folderPath });
        if (selectedFolderId === folder.id) setSelectedFolderId(null);
        loadAllManufacturerFolders();
        showSuccessToast('Folder deleted');
      } catch (error) {
        const errorMessage = error instanceof Error ? error.message : 'Failed to delete folder';
        setFolderError(errorMessage);
        showErrorToast('Failed to delete folder', { description: errorMessage });
      }
    }
  };

  const handleAddSubfolder = (parentFolder: SpecSheetFolder) => {
    setNewFolderParentId(parentFolder.id);
    setNewFolderManufacturer(parentFolder.manufacturer || '');
    setNewFolderName('');
    setShowAddFolderModal(true);
  };

  const handleAddRootFolder = (manufacturer: string, manufacturerId?: string) => {
    setNewFolderParentId(null);
    setNewFolderManufacturer(manufacturer);
    const id = manufacturerId || findManufacturerIdByName(manufacturer);
    setNewFolderManufacturerId(id || '');
    setNewFolderName('');
    setShowAddFolderModal(true);
  };

  const handleCreateFolder = async () => {
    if (!newFolderName.trim() || !newFolderManufacturerId) return;
    let parentPath = '';
    if (newFolderParentId) {
      const parentFolderPath = getFolderPath(newFolderParentId);
      parentPath = parentFolderPath || '';
    }
    setFolderError(null);
    try {
      await createFolderMutation.mutateAsync({ factoryId: newFolderManufacturerId, parentPath, folderName: newFolderName.trim() });
      setShowAddFolderModal(false);
      setNewFolderName('');
      if (newFolderParentId) setExpandedFolders(prev => new Set([...prev, newFolderParentId!]));
      if (newFolderManufacturer) setExpandedManufacturers(prev => new Set([...prev, newFolderManufacturer]));
      loadAllManufacturerFolders(true);
    } catch (error) {
      setFolderError(error instanceof Error ? error.message : 'Failed to create folder');
    }
  };

  const handleFolderDragStart = (e: React.DragEvent, folderId: string) => { e.stopPropagation(); setDraggedFolderId(folderId); e.dataTransfer.effectAllowed = 'move'; };
  const handleFolderDragOver = (e: React.DragEvent, folderId: string) => {
    e.preventDefault(); e.stopPropagation();
    if (draggedFolderId && draggedFolderId !== folderId) {
      const isChild = (parentId: string, childId: string): boolean => {
        const children = folders.filter(f => f.parentId === parentId);
        if (children.some(c => c.id === childId)) return true;
        return children.some(c => isChild(c.id, childId));
      };
      if (!isChild(draggedFolderId, folderId)) setDragOverFolderId(folderId);
    }
  };
  const handleFolderDragLeave = (e: React.DragEvent) => { e.stopPropagation(); setDragOverFolderId(null); };
  const handleFolderDrop = (e: React.DragEvent) => {
    e.preventDefault(); e.stopPropagation();
    setFolderError('Moving folders is not yet supported');
    setDraggedFolderId(null);
    setDragOverFolderId(null);
  };
  const handleFolderDragEnd = () => { setDraggedFolderId(null); setDragOverFolderId(null); };

  const getAllFoldersForManufacturer = (manufacturerName: string): SpecSheetFolder[] => {
    const manufacturerData = manufacturers.find(m => m.name === manufacturerName);
    if (!manufacturerData) return [];
    const apiFolders = allManufacturerFolders[manufacturerData.id] || [];
    if (apiFolders.length === 0) return [];
    const folderMap = new Map<string, SpecSheetFolder>();
    for (const apiFolder of apiFolders) {
      const parts = apiFolder.folderPath.split('/').filter(Boolean);
      const folderName = parts[parts.length - 1] || apiFolder.folderPath;
      folderMap.set(apiFolder.folderPath, {
        id: apiFolder.id, name: folderName, parentId: null, manufacturer: manufacturerName,
        isAutoGenerated: false, createdAt: apiFolder.createdAt || '', createdBy: 'System',
        specSheetCount: apiFolder.specSheetCount, folderPath: apiFolder.folderPath,
      });
    }
    for (const apiFolder of apiFolders) {
      const parts = apiFolder.folderPath.split('/').filter(Boolean);
      if (parts.length > 1) {
        const parentPath = parts.slice(0, -1).join('/');
        const parentFolder = apiFolders.find(f => f.folderPath === parentPath);
        if (parentFolder) {
          const folder = folderMap.get(apiFolder.folderPath);
          if (folder) folder.parentId = parentFolder.id;
        }
      }
    }
    return Array.from(folderMap.values()).filter(f => f.parentId === null);
  };

  // Uses allManufacturerFolders so it works even when manufacturer is not selected
  const getFoldersForManufacturer = (manufacturer: string) => getAllFoldersForManufacturer(manufacturer);

  const getChildFoldersFromAll = (parentId: string, manufacturerName: string): SpecSheetFolder[] => {
    const manufacturerData = manufacturers.find(m => m.name === manufacturerName);
    if (!manufacturerData) return [];
    const apiFolders = allManufacturerFolders[manufacturerData.id] || [];
    if (apiFolders.length === 0) return [];
    const parentFolder = apiFolders.find(f => f.id === parentId);
    if (!parentFolder) return [];
    const children: SpecSheetFolder[] = [];
    for (const apiFolder of apiFolders) {
      const parts = apiFolder.folderPath.split('/').filter(Boolean);
      if (parts.length > 1) {
        const folderParentPath = parts.slice(0, -1).join('/');
        if (folderParentPath === parentFolder.folderPath) {
          children.push({
            id: apiFolder.id, name: parts[parts.length - 1], parentId, manufacturer: manufacturerName,
            isAutoGenerated: false, createdAt: apiFolder.createdAt || '', createdBy: 'System',
            specSheetCount: apiFolder.specSheetCount, folderPath: apiFolder.folderPath,
          });
        }
      }
    }
    return children;
  };

  const getFolderCountForManufacturer = (manufacturerName: string): number => {
    const manufacturerData = manufacturers.find(m => m.name === manufacturerName);
    if (!manufacturerData) return 0;
    return (allManufacturerFolders[manufacturerData.id] || []).length;
  };

  const getFolderSpecSheetCount = (folderId: string, manufacturerName: string): number => {
    const manufacturerData = manufacturers.find(m => m.name === manufacturerName);
    if (!manufacturerData) return 0;
    const apiFolders = allManufacturerFolders[manufacturerData.id] || [];
    const folder = apiFolders.find(f => f.id === folderId);
    return folder?.specSheetCount || 0;
  };

  const getChildFoldersLocal = (parentId: string) => folders.filter(f => f.parentId === parentId);

  const toggleFolder = (folderId: string) => {
    setExpandedFolders(prev => {
      const next = new Set(prev);
      if (next.has(folderId)) next.delete(folderId);
      else next.add(folderId);
      return next;
    });
  };

  const toggleManufacturer = (manufacturer: string) => {
    setExpandedManufacturers(prev => {
      const next = new Set(prev);
      if (next.has(manufacturer)) next.delete(manufacturer);
      else next.add(manufacturer);
      return next;
    });
  };

  const getFolderCount = (folderId: string): number => {
    const folder = folders.find(f => f.id === folderId);
    return folder?.specSheetCount || 0;
  };

  return {
    // State
    expandedFolders,
    selectedFolderId,
    setSelectedFolderId,
    expandedManufacturers,
    contextMenu,
    setContextMenu,
    editingFolderId,
    setEditingFolderId,
    editingFolderName,
    setEditingFolderName,
    showAddFolderModal,
    setShowAddFolderModal,
    newFolderParentId,
    newFolderManufacturer,
    newFolderName,
    setNewFolderName,
    draggedFolderId,
    dragOverFolderId,
    setDragOverFolderId,
    folderError,
    setFolderError,
    folders,
    isSavingFolder,
    isCreatingFolder,
    isLoadingFolders,
    isLoadingAllFolders,

    // Handlers
    toggleFolder,
    toggleManufacturer,
    handleFolderContextMenu,
    handleRenameFolder,
    handleSaveRename,
    handleDeleteFolder,
    handleAddSubfolder,
    handleAddRootFolder,
    handleCreateFolder,
    handleFolderDragStart,
    handleFolderDragOver,
    handleFolderDragLeave,
    handleFolderDrop,
    handleFolderDragEnd,
    getFoldersForManufacturer,
    getAllFoldersForManufacturer,
    getChildFoldersFromAll,
    getFolderCountForManufacturer,
    getFolderSpecSheetCount,
    getChildFoldersLocal,
    getFolderCount,
    loadAllManufacturerFolders,
  };
}
