'use client';

import React, { useState, useMemo, useRef, useEffect } from 'react';
// API Hooks
import {
  useManufacturersWithSpecSheets,
  useSpecSheetSearch,
  useFoldersByFactory,
  useCreateFolder,
  useRenameFolder,
  useDeleteFolder,
} from './api/useSpecSheetsApi';
import type { SpecSheet, SpecSheetFolder, SpecSheetCategory } from '../../lib/types/submittals';
import { specSheetCategoryLabels } from '../../lib/data/submittals-mock';
import { fetchFoldersByFactory as fetchFoldersApi, type FolderResponse } from '../lib/graphql/spec-sheets';

// Extracted components
import { SpecSheetCard, SpecSheetListItem } from './SpecSheetDisplayItems';
import { FolderContextMenu } from './FolderContextMenu';
import { ManufacturerManagementModal } from './ManufacturerManagementModal';
import { AddFolderModal } from './AddFolderModal';

/**
 * Derive folders from spec sheets' folder paths.
 * Creates a folder tree structure from the folder_path strings.
 */
function deriveFoldersFromSpecSheets(specSheets: SpecSheet[], manufacturerName: string): SpecSheetFolder[] {
  const folders: SpecSheetFolder[] = [];
  const folderPaths = new Set<string>();

  // Collect all unique folder paths
  for (const sheet of specSheets) {
    // The sheet may have folderPath (from API transformation)
    const path = (sheet as unknown as { folderPath?: string }).folderPath;
    if (path && typeof path === 'string' && path.trim()) {
      folderPaths.add(path.trim());
    }
  }

  // Convert folder paths to folder objects
  // Paths can be like "Linear", "Linear/Indoor", etc.
  const processedPaths = new Map<string, string>(); // path -> id

  for (const path of folderPaths) {
    const parts = path.split('/').filter(Boolean);
    let currentPath = '';

    for (let i = 0; i < parts.length; i++) {
      const part = parts[i];
      const parentPath = currentPath;
      currentPath = currentPath ? `${currentPath}/${part}` : part;

      if (!processedPaths.has(currentPath)) {
        const id = `folder-${manufacturerName}-${currentPath}`.replace(/[^a-zA-Z0-9-]/g, '-');
        processedPaths.set(currentPath, id);

        const parentId = parentPath ? processedPaths.get(parentPath) || null : null;

        folders.push({
          id,
          name: part,
          parentId,
          manufacturer: manufacturerName,
          isAutoGenerated: true,
          createdAt: new Date().toISOString(),
          createdBy: 'System',
        });
      }
    }
  }

  return folders;
}
import SpecSheetUploadModal from './SpecSheetUploadModal';
import SpecSheetViewerModal from './SpecSheetViewerModal';

type HighlightFilter = 'all' | 'highlighted' | 'not_highlighted';

export default function SpecSheetsContent() {
  const [selectedSpecSheet, setSelectedSpecSheet] = useState<SpecSheet | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [showUploadModal, setShowUploadModal] = useState(false);
  const [viewMode, setViewMode] = useState<'grid' | 'list'>('grid');

  // Filter state - selectedManufacturerId is the factory UUID
  const [selectedManufacturerId, setSelectedManufacturerId] = useState<string | null>(null);
  const [selectedTags, setSelectedTags] = useState<string[]>([]);
  const [highlightFilter, setHighlightFilter] = useState<HighlightFilter>('all');

  // Folder navigation
  const [expandedFolders, setExpandedFolders] = useState<Set<string>>(new Set());
  const [selectedFolderId, setSelectedFolderId] = useState<string | null>(null);
  const [expandedManufacturers, setExpandedManufacturers] = useState<Set<string>>(new Set());

  // Collapsible sections
  const [sectionsExpanded, setSectionsExpanded] = useState({
    tags: false,
    highlights: false,
    manufacturers: true,
  });

  // Open Catalog modal
  const [showCatalogModal, setShowCatalogModal] = useState(false);

  // Manufacturer management modal
  const [showManufacturerModal, setShowManufacturerModal] = useState(false);
  const [editingManufacturerIndex, setEditingManufacturerIndex] = useState<number | null>(null);
  const [editingManufacturerName, setEditingManufacturerName] = useState('');
  const [draggedManufacturerIndex, setDraggedManufacturerIndex] = useState<number | null>(null);
  const [dragOverIndex, setDragOverIndex] = useState<number | null>(null);

  // State for folders of all manufacturers (for the Manage Manufacturers modal)
  const [allManufacturerFolders, setAllManufacturerFolders] = useState<Record<string, FolderResponse[]>>({});
  const [isLoadingAllFolders, setIsLoadingAllFolders] = useState(false);
  const hasLoadedFoldersRef = useRef(false);

  // ============================================================================
  // API Hooks
  // ============================================================================

  // Fetch manufacturers (factories)
  const {
    data: manufacturers = [],
    isLoading: isLoadingManufacturers,
    error: manufacturersError
  } = useManufacturersWithSpecSheets();

  // When searching, don't filter by manufacturer to show all results
  // Only filter by manufacturer when not searching and a manufacturer is selected
  const searchManufacturerId = searchQuery ? undefined : selectedManufacturerId;

  // Fetch spec sheets - supports "All Manufacturers" (null) and search
  const {
    data: specSheetsData,
    isLoading: isLoadingSpecSheets,
    error: specSheetsError
  } = useSpecSheetSearch({
    searchTerm: searchQuery || undefined,
    factoryId: searchManufacturerId || undefined,
    publishedOnly: false,
    limit: 500,
  });

  // Separate query for ALL spec sheets (for Tags, Highlights, and Manufacturers counts)
  // This query has no filters so counts reflect the full dataset
  // Note: Use empty string '' instead of undefined for searchTerm to ensure query returns results
  const { data: allSpecSheetsData } = useSpecSheetSearch({
    searchTerm: '',
    factoryId: undefined,
    publishedOnly: false,
    limit: 1000,
  });

  // Fetch folders for selected manufacturer
  const {
    data: foldersData,
    isLoading: isLoadingFolders,
  } = useFoldersByFactory(selectedManufacturerId);

  // Folder mutations
  const createFolderMutation = useCreateFolder();
  const renameFolderMutation = useRenameFolder();
  const deleteFolderMutation = useDeleteFolder();

  // Track mutation states
  const isSavingFolder = renameFolderMutation.isPending || deleteFolderMutation.isPending;
  const isCreatingFolder = createFolderMutation.isPending;

  // Error state for folder operations
  const [folderError, setFolderError] = useState<string | null>(null);

  // Combined error state for display
  const apiError = manufacturersError || specSheetsError;

  // Function to load folders for all manufacturers (for Manage Manufacturers modal)
  const loadAllManufacturerFolders = async (force = false) => {
    if (!manufacturers || manufacturers.length === 0) return;
    if (isLoadingAllFolders) return; // Prevent concurrent loads
    if (hasLoadedFoldersRef.current && !force) return; // Already loaded, skip unless forced

    setIsLoadingAllFolders(true);
    try {
      const foldersMap: Record<string, FolderResponse[]> = {};
      await Promise.all(
        manufacturers.map(async (m) => {
          try {
            const folders = await fetchFoldersApi(m.id);
            foldersMap[m.id] = folders;
          } catch (error) {
            console.error(`Failed to fetch folders for manufacturer ${m.id}:`, error);
            foldersMap[m.id] = [];
          }
        })
      );
      setAllManufacturerFolders(foldersMap);
      hasLoadedFoldersRef.current = true;
    } finally {
      setIsLoadingAllFolders(false);
    }
  };

  // Load folders for all manufacturers when manufacturers data is available (only once)
  useEffect(() => {
    if (manufacturers && manufacturers.length > 0 && !hasLoadedFoldersRef.current) {
      loadAllManufacturerFolders();
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [manufacturers]);

  // Transform API response to frontend SpecSheet type
  const specSheets: SpecSheet[] = useMemo(() => {
    if (!specSheetsData) return [];

    return specSheetsData.map(sheet => {
      // Find the manufacturer name from the sheet's factoryId
      const manufacturer = manufacturers.find(m => m.id === sheet.factoryId);
      const manufacturerName = manufacturer?.name || 'Unknown';

      return {
        id: sheet.id,
        manufacturer: manufacturerName,
        fileName: sheet.fileName,
        displayName: sheet.displayName,
        categories: sheet.categories as SpecSheet['categories'],
        tags: sheet.tags || [],
        folderId: undefined,
        folderPath: sheet.folderPath || undefined,
        uploadSource: sheet.uploadSource as SpecSheet['uploadSource'],
        sourceUrl: sheet.sourceUrl || undefined,
        fileUrl: sheet.fileUrl,
        fileSize: sheet.fileSize,
        pageCount: sheet.pageCount,
        uploadedAt: sheet.createdAt,
        uploadedBy: sheet.createdBy.fullName,
        needsReview: sheet.needsReview,
        usageCount: sheet.usageCount,
        highlightCount: sheet.highlightCount,
      };
    });
  }, [specSheetsData, manufacturers]);

  // Transform ALL spec sheets for sidebar counts (categories, manufacturers, highlights)
  const allSpecSheets: SpecSheet[] = useMemo(() => {
    if (!allSpecSheetsData) return [];

    return allSpecSheetsData.map(sheet => {
      const manufacturer = manufacturers.find(m => m.id === sheet.factoryId);
      const manufacturerName = manufacturer?.name || 'Unknown';

      return {
        id: sheet.id,
        manufacturer: manufacturerName,
        fileName: sheet.fileName,
        displayName: sheet.displayName,
        categories: sheet.categories as SpecSheet['categories'],
        tags: sheet.tags || [],
        folderId: undefined,
        folderPath: sheet.folderPath || undefined,
        uploadSource: sheet.uploadSource as SpecSheet['uploadSource'],
        sourceUrl: sheet.sourceUrl || undefined,
        fileUrl: sheet.fileUrl,
        fileSize: sheet.fileSize,
        pageCount: sheet.pageCount,
        uploadedAt: sheet.createdAt,
        uploadedBy: sheet.createdBy.fullName,
        needsReview: sheet.needsReview,
        usageCount: sheet.usageCount,
        highlightCount: sheet.highlightCount,
      };
    });
  }, [allSpecSheetsData, manufacturers]);

  // Get the selected manufacturer name for display
  const selectedManufacturer = useMemo(() => {
    if (!selectedManufacturerId) return '';
    return manufacturers.find(m => m.id === selectedManufacturerId)?.name || '';
  }, [selectedManufacturerId, manufacturers]);

  // Derive manufacturer list from API data
  const manufacturerList = useMemo(() => {
    return manufacturers.map(m => m.name);
  }, [manufacturers]);

  // Helper to find factory ID by name (for compatibility with folder data)
  const findManufacturerIdByName = (name: string): string | null => {
    const found = manufacturers.find(m => m.name === name);
    return found?.id || null;
  };

  // Helper to select manufacturer by name (for folder clicks)
  const selectManufacturerByName = (name: string) => {
    const id = findManufacturerIdByName(name);
    if (id) setSelectedManufacturerId(id);
  };

  // Convert API folder data to SpecSheetFolder format
  const folders: SpecSheetFolder[] = useMemo(() => {
    if (!foldersData) return [];

    const selectedManufacturer = manufacturers.find(m => m.id === selectedManufacturerId);
    const manufacturerName = selectedManufacturer?.name || '';

    // Build folder hierarchy from flat API data
    const folderMap = new Map<string, SpecSheetFolder>();

    // First pass: create all folders
    for (const apiFolder of foldersData) {
      const parts = apiFolder.folderPath.split('/').filter(Boolean);
      const folderName = parts[parts.length - 1] || apiFolder.folderPath;
      const parentPath = parts.length > 1 ? parts.slice(0, -1).join('/') : null;

      folderMap.set(apiFolder.folderPath, {
        id: apiFolder.id,
        name: folderName,
        parentId: null, // Will be set in second pass
        manufacturer: manufacturerName,
        isAutoGenerated: false,
        createdAt: apiFolder.createdAt || '',
        createdBy: 'System',
        specSheetCount: apiFolder.specSheetCount,
        folderPath: apiFolder.folderPath,
      });
    }

    // Second pass: set parent IDs
    for (const apiFolder of foldersData) {
      const parts = apiFolder.folderPath.split('/').filter(Boolean);
      if (parts.length > 1) {
        const parentPath = parts.slice(0, -1).join('/');
        const parentFolder = foldersData.find(f => f.folderPath === parentPath);
        if (parentFolder) {
          const folder = folderMap.get(apiFolder.folderPath);
          if (folder) {
            folder.parentId = parentFolder.id;
          }
        }
      }
    }

    return Array.from(folderMap.values());
  }, [foldersData, selectedManufacturerId, manufacturers]);
  const [contextMenu, setContextMenu] = useState<{ folder: SpecSheetFolder; position: { x: number; y: number } } | null>(null);
  const [editingFolderId, setEditingFolderId] = useState<string | null>(null);
  const [editingFolderName, setEditingFolderName] = useState('');
  const [showAddFolderModal, setShowAddFolderModal] = useState(false);
  const [newFolderParentId, setNewFolderParentId] = useState<string | null>(null);
  const [newFolderManufacturer, setNewFolderManufacturer] = useState<string>('');
  const [newFolderManufacturerId, setNewFolderManufacturerId] = useState<string>('');
  const [newFolderName, setNewFolderName] = useState('');

  // Folder drag-and-drop state
  const [draggedFolderId, setDraggedFolderId] = useState<string | null>(null);
  const [dragOverFolderId, setDragOverFolderId] = useState<string | null>(null);

  const toggleSection = (section: keyof typeof sectionsExpanded) => {
    setSectionsExpanded(prev => ({ ...prev, [section]: !prev[section] }));
  };

  // Manufacturer management functions
  const handleDragStart = (index: number) => {
    setDraggedManufacturerIndex(index);
  };

  const handleDragOver = (e: React.DragEvent, index: number) => {
    e.preventDefault();
    setDragOverIndex(index);
  };

  const handleDragLeave = () => {
    setDragOverIndex(null);
  };

  const handleDrop = (_index: number) => {
    // Manufacturer reordering is not supported when using API data
    // Ordering should be managed through the manufacturer settings page
    setDraggedManufacturerIndex(null);
    setDragOverIndex(null);
  };

  const handleDragEnd = () => {
    setDraggedManufacturerIndex(null);
    setDragOverIndex(null);
  };

  const handleRenameManufacturer = (_index: number) => {
    // Manufacturer renaming should be done through the manufacturer settings page
    alert('To rename a manufacturer, please use the Manufacturers page in Settings.');
  };

  const handleSaveManufacturerRename = () => {
    setEditingManufacturerIndex(null);
    setEditingManufacturerName('');
  };

  const handleDeleteManufacturer = (_index: number) => {
    // Manufacturer deletion should be done through the manufacturer settings page
    alert('To delete a manufacturer, please use the Manufacturers page in Settings.');
  };

  const handleAddManufacturer = () => {
    // Manufacturer creation should be done through the manufacturer settings page
    alert('To add a new manufacturer, please use the Manufacturers page in Settings.');
  };

  // Folder management functions
  const handleFolderContextMenu = (e: React.MouseEvent, folder: SpecSheetFolder) => {
    e.preventDefault();
    e.stopPropagation();
    setContextMenu({ folder, position: { x: e.clientX, y: e.clientY } });
  };

  // Helper to get folder path from folder ID
  const getFolderPath = (folderId: string): string | null => {
    if (!foldersData) return null;
    const folder = foldersData.find(f => f.id === folderId);
    return folder?.folderPath || null;
  };

  const handleRenameFolder = (folder: SpecSheetFolder) => {
    setEditingFolderId(folder.id);
    setEditingFolderName(folder.name);
  };

  const handleSaveRename = async () => {
    if (!editingFolderId || !editingFolderName.trim() || !selectedManufacturerId) {
      setEditingFolderId(null);
      setEditingFolderName('');
      return;
    }

    const folderPath = getFolderPath(editingFolderId);
    if (!folderPath) {
      setEditingFolderId(null);
      setEditingFolderName('');
      return;
    }

    setFolderError(null);
    try {
      await renameFolderMutation.mutateAsync({
        factoryId: selectedManufacturerId,
        folderPath,
        newName: editingFolderName.trim(),
      });
      // Refresh folders for all manufacturers (force reload)
      loadAllManufacturerFolders(true);
    } catch (error) {
      setFolderError(error instanceof Error ? error.message : 'Failed to rename folder');
    } finally {
      setEditingFolderId(null);
      setEditingFolderName('');
    }
  };

  const handleDeleteFolder = async (folder: SpecSheetFolder) => {
    if (!selectedManufacturerId) return;

    const folderPath = getFolderPath(folder.id);
    if (!folderPath) return;

    if (confirm(`Delete folder "${folder.name}"? This will not delete the spec sheets inside.`)) {
      setFolderError(null);
      try {
        await deleteFolderMutation.mutateAsync({
          factoryId: selectedManufacturerId,
          folderPath,
        });
        if (selectedFolderId === folder.id) {
          setSelectedFolderId(null);
        }
        // Refresh folders for all manufacturers
        loadAllManufacturerFolders();
      } catch (error) {
        setFolderError(error instanceof Error ? error.message : 'Failed to delete folder');
      }
    }
  };

  const handleAddSubfolder = (parentFolder: SpecSheetFolder) => {
    setNewFolderParentId(parentFolder.id);
    setNewFolderManufacturer(parentFolder.manufacturer || '');
    setNewFolderName('');
    setShowAddFolderModal(true);
  };

  const handleAddRootFolder = (manufacturer: string, manufacturerId?: string) => {
    setNewFolderParentId(null);
    setNewFolderManufacturer(manufacturer);
    // Use provided ID or look it up by name
    const id = manufacturerId || findManufacturerIdByName(manufacturer);
    setNewFolderManufacturerId(id || '');
    setNewFolderName('');
    setShowAddFolderModal(true);
  };

  const handleCreateFolder = async () => {
    if (!newFolderName.trim() || !newFolderManufacturerId) return;

    // Get parent path for the new folder
    let parentPath = '';
    if (newFolderParentId) {
      const parentFolderPath = getFolderPath(newFolderParentId);
      parentPath = parentFolderPath || '';
    }

    setFolderError(null);
    try {
      await createFolderMutation.mutateAsync({
        factoryId: newFolderManufacturerId,
        parentPath,
        folderName: newFolderName.trim(),
      });

      setShowAddFolderModal(false);
      setNewFolderName('');

      // Expand parent if adding subfolder
      if (newFolderParentId) {
        setExpandedFolders(prev => new Set([...prev, newFolderParentId!]));
      }
      // Also expand manufacturer
      if (newFolderManufacturer) {
        setExpandedManufacturers(prev => new Set([...prev, newFolderManufacturer]));
      }
      // Refresh folders for all manufacturers (force reload)
      loadAllManufacturerFolders(true);
    } catch (error) {
      setFolderError(error instanceof Error ? error.message : 'Failed to create folder');
    }
  };

  // Folder drag-and-drop handlers
  const handleFolderDragStart = (e: React.DragEvent, folderId: string) => {
    e.stopPropagation();
    setDraggedFolderId(folderId);
    e.dataTransfer.effectAllowed = 'move';
  };

  const handleFolderDragOver = (e: React.DragEvent, folderId: string) => {
    e.preventDefault();
    e.stopPropagation();
    if (draggedFolderId && draggedFolderId !== folderId) {
      // Don't allow dropping on own children
      const isChild = (parentId: string, childId: string): boolean => {
        const children = folders.filter(f => f.parentId === parentId);
        if (children.some(c => c.id === childId)) return true;
        return children.some(c => isChild(c.id, childId));
      };
      if (!isChild(draggedFolderId, folderId)) {
        setDragOverFolderId(folderId);
      }
    }
  };

  const handleFolderDragLeave = (e: React.DragEvent) => {
    e.stopPropagation();
    setDragOverFolderId(null);
  };

  const handleFolderDrop = (e: React.DragEvent, _targetFolderId: string | null, _targetManufacturer?: string) => {
    e.preventDefault();
    e.stopPropagation();

    // Moving folders is not yet implemented via API
    // Would need a moveFolder mutation
    setFolderError('Moving folders is not yet supported');
    setDraggedFolderId(null);
    setDragOverFolderId(null);
  };

  const handleFolderDragEnd = () => {
    setDraggedFolderId(null);
    setDragOverFolderId(null);
  };

  // Get folders for manufacturer using local state (for selected manufacturer only)
  const getFoldersForManufacturer = (manufacturer: string) => {
    return folders.filter(f => f.manufacturer === manufacturer && f.parentId === null);
  };

  // Get ALL folders for a manufacturer (for Manage Manufacturers modal)
  // This uses allManufacturerFolders which has data for all manufacturers
  const getAllFoldersForManufacturer = (manufacturerName: string): SpecSheetFolder[] => {
    const manufacturerData = manufacturers.find(m => m.name === manufacturerName);
    if (!manufacturerData) return [];

    const apiFolders = allManufacturerFolders[manufacturerData.id] || [];
    if (apiFolders.length === 0) return [];

    // Build folder hierarchy from flat API data
    const folderMap = new Map<string, SpecSheetFolder>();

    // First pass: create all folders
    for (const apiFolder of apiFolders) {
      const parts = apiFolder.folderPath.split('/').filter(Boolean);
      const folderName = parts[parts.length - 1] || apiFolder.folderPath;
      const parentPath = parts.length > 1 ? parts.slice(0, -1).join('/') : null;

      folderMap.set(apiFolder.folderPath, {
        id: apiFolder.id,
        name: folderName,
        parentId: null, // Will be set in second pass
        manufacturer: manufacturerName,
        isAutoGenerated: false,
        createdAt: apiFolder.createdAt || '',
        createdBy: 'System',
        specSheetCount: apiFolder.specSheetCount,
        folderPath: apiFolder.folderPath,
      });
    }

    // Second pass: set parent IDs
    for (const apiFolder of apiFolders) {
      const parts = apiFolder.folderPath.split('/').filter(Boolean);
      if (parts.length > 1) {
        const parentPath = parts.slice(0, -1).join('/');
        const parentFolder = apiFolders.find(f => f.folderPath === parentPath);
        if (parentFolder) {
          const folder = folderMap.get(apiFolder.folderPath);
          if (folder) {
            folder.parentId = parentFolder.id;
          }
        }
      }
    }

    // Return only root-level folders
    return Array.from(folderMap.values()).filter(f => f.parentId === null);
  };

  // Get child folders from allManufacturerFolders (for modal)
  const getChildFoldersFromAll = (parentId: string, manufacturerName: string): SpecSheetFolder[] => {
    const manufacturerData = manufacturers.find(m => m.name === manufacturerName);
    if (!manufacturerData) return [];

    const apiFolders = allManufacturerFolders[manufacturerData.id] || [];
    if (apiFolders.length === 0) return [];

    // Find parent folder path
    const parentFolder = apiFolders.find(f => f.id === parentId);
    if (!parentFolder) return [];

    // Find direct children
    const children: SpecSheetFolder[] = [];
    for (const apiFolder of apiFolders) {
      const parts = apiFolder.folderPath.split('/').filter(Boolean);
      if (parts.length > 1) {
        const folderParentPath = parts.slice(0, -1).join('/');
        if (folderParentPath === parentFolder.folderPath) {
          children.push({
            id: apiFolder.id,
            name: parts[parts.length - 1],
            parentId: parentId,
            manufacturer: manufacturerName,
            isAutoGenerated: false,
            createdAt: apiFolder.createdAt || '',
            createdBy: 'System',
            specSheetCount: apiFolder.specSheetCount,
            folderPath: apiFolder.folderPath,
          });
        }
      }
    }

    return children;
  };

  // Get folder count for a manufacturer (from allManufacturerFolders)
  const getFolderCountForManufacturer = (manufacturerName: string): number => {
    const manufacturerData = manufacturers.find(m => m.name === manufacturerName);
    if (!manufacturerData) return 0;
    return (allManufacturerFolders[manufacturerData.id] || []).length;
  };

  // Get spec sheet count in a folder (from allManufacturerFolders)
  // Note: The API returns recursive counts (includes all spec sheets in folder AND subfolders)
  const getFolderSpecSheetCount = (folderId: string, manufacturerName: string): number => {
    const manufacturerData = manufacturers.find(m => m.name === manufacturerName);
    if (!manufacturerData) return 0;
    const apiFolders = allManufacturerFolders[manufacturerData.id] || [];
    const folder = apiFolders.find(f => f.id === folderId);
    return folder?.specSheetCount || 0;
  };

  // Get child folders using local state
  const getChildFoldersLocal = (parentId: string) => {
    return folders.filter(f => f.parentId === parentId);
  };

  // Derive all unique categories from ALL spec sheets (not filtered)
  const allCategories = useMemo(() => {
    const cats = new Set<SpecSheetCategory>();
    allSpecSheets.forEach(sheet => {
      if (sheet.categories && Array.isArray(sheet.categories)) {
        sheet.categories.forEach(cat => cats.add(cat));
      }
    });
    return Array.from(cats).sort();
  }, [allSpecSheets]);

  // Filter spec sheets (already filtered by manufacturer via API)
  const filteredSpecSheets = useMemo(() => {
    let result = [...specSheets];

    // Folder filter (hierarchical - includes subfolders)
    if (selectedFolderId) {
      const selectedFolder = folders.find(f => f.id === selectedFolderId);
      if (selectedFolder?.folderPath) {
        const selectedPath = selectedFolder.folderPath;
        result = result.filter(s => {
          if (!s.folderPath) return false;
          // Match exact folder or any subfolder
          return s.folderPath === selectedPath || s.folderPath.startsWith(selectedPath + '/');
        });
      }
    }

    // Categories filter (match any selected category)
    if (selectedTags.length > 0) {
      result = result.filter(s =>
        s.categories && selectedTags.some(cat => s.categories.includes(cat as SpecSheetCategory))
      );
    }

    // Highlight filter
    if (highlightFilter === 'highlighted') {
      result = result.filter(s => (s.highlightCount || 0) > 0);
    } else if (highlightFilter === 'not_highlighted') {
      result = result.filter(s => (s.highlightCount || 0) === 0);
    }

    // Note: Search is now handled server-side by useSpecSheetSearch

    return result.sort((a, b) => a.displayName.localeCompare(b.displayName));
  }, [specSheets, selectedFolderId, folders, selectedTags, highlightFilter]);

  // Get highlight count for a spec sheet (from API data)
  const getHighlightCount = (specSheetId: string) => {
    const sheet = specSheets.find(s => s.id === specSheetId);
    return sheet?.highlightCount || 0;
  };

  // Toggle folder expansion
  const toggleFolder = (folderId: string) => {
    setExpandedFolders(prev => {
      const next = new Set(prev);
      if (next.has(folderId)) {
        next.delete(folderId);
      } else {
        next.add(folderId);
      }
      return next;
    });
  };

  // Toggle manufacturer expansion
  const toggleManufacturer = (manufacturer: string) => {
    setExpandedManufacturers(prev => {
      const next = new Set(prev);
      if (next.has(manufacturer)) {
        next.delete(manufacturer);
      } else {
        next.add(manufacturer);
      }
      return next;
    });
  };

  // Clear all filters (but keep manufacturer selection to avoid flash)
  const clearFilters = () => {
    // Note: We intentionally do NOT reset selectedManufacturerId
    // Manufacturer is more of a "scope" than a "filter"
    // Resetting it would cause a flash as auto-select re-triggers
    setSelectedTags([]);
    setHighlightFilter('all');
    setSelectedFolderId(null);
    setSearchQuery('');
  };

  // hasActiveFilters does NOT include selectedManufacturerId (it's always set)
  const hasActiveFilters = selectedTags.length > 0 || highlightFilter !== 'all' || selectedFolderId || searchQuery;

  // Count spec sheets per manufacturer (from ALL spec sheets, not filtered)
  const manufacturerCounts = useMemo(() => {
    const counts: Record<string, number> = {};
    allSpecSheets.forEach(s => {
      counts[s.manufacturer] = (counts[s.manufacturer] || 0) + 1;
    });
    return counts;
  }, [allSpecSheets]);

  // Count spec sheets in folder (uses API-provided count which is already recursive)
  // The backend returns counts that include all spec sheets in the folder AND subfolders
  const getFolderCount = (folderId: string): number => {
    const folder = folders.find(f => f.id === folderId);
    return folder?.specSheetCount || 0;
  };

  // Render folder tree recursively
  const renderFolderTree = (folderList: SpecSheetFolder[], depth: number = 0) => {
    return folderList.map(folder => {
      const childFolders = getChildFoldersLocal(folder.id);
      const hasChildren = childFolders.length > 0;
      const isExpanded = expandedFolders.has(folder.id);
      const isSelected = selectedFolderId === folder.id;
      const isEditing = editingFolderId === folder.id;
      // API returns recursive counts (includes all spec sheets in folder and subfolders)
      // Show count when collapsed, hide when expanded (children show their own counts)
      const count = hasChildren && isExpanded ? null : getFolderCount(folder.id);

      return (
        <div key={folder.id}>
          <div
            onClick={() => {
              if (!isEditing) {
                if (hasChildren) toggleFolder(folder.id);
                setSelectedFolderId(isSelected ? null : folder.id);
                if (folder.manufacturer) selectManufacturerByName(folder.manufacturer);
              }
            }}
            onContextMenu={(e) => handleFolderContextMenu(e, folder)}
            className={`w-full flex items-center gap-2 px-3 py-1.5 text-sm hover:bg-[var(--muted)]/50 transition-colors cursor-pointer group ${
              isSelected ? 'bg-[var(--primary)]/10 text-[var(--primary)]' : 'text-[var(--foreground)]'
            }`}
            style={{ paddingLeft: `${12 + depth * 16}px` }}
          >
            {hasChildren ? (
              <svg
                width="12"
                height="12"
                viewBox="0 0 20 20"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                className={`transition-transform flex-shrink-0 ${isExpanded ? 'rotate-90' : ''}`}
              >
                <path d="M7 5l5 5-5 5" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            ) : (
              <span className="w-3 flex-shrink-0" />
            )}
            <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-[var(--muted-foreground)] flex-shrink-0">
              <path d="M3 5a2 2 0 012-2h3.172a2 2 0 011.414.586l.828.828a2 2 0 001.414.586H15a2 2 0 012 2v7a2 2 0 01-2 2H5a2 2 0 01-2-2V5z"/>
            </svg>
            {isEditing ? (
              <input
                type="text"
                value={editingFolderName}
                onChange={(e) => setEditingFolderName(e.target.value)}
                onBlur={handleSaveRename}
                onKeyDown={(e) => {
                  if (e.key === 'Enter') handleSaveRename();
                  if (e.key === 'Escape') {
                    setEditingFolderId(null);
                    setEditingFolderName('');
                  }
                }}
                autoFocus
                onClick={(e) => e.stopPropagation()}
                className="flex-1 px-1 py-0.5 text-sm border border-[var(--primary)] rounded bg-[var(--background)] focus:outline-none"
              />
            ) : (
              <span className="flex-1 truncate text-left">{folder.name}</span>
            )}
            {count !== null && count > 0 && !isEditing && (
              <span className="text-xs text-[var(--muted-foreground)]">{count}</span>
            )}
            {!isEditing && (
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  handleFolderContextMenu(e, folder);
                }}
                className="opacity-0 group-hover:opacity-100 p-0.5 hover:bg-[var(--muted)] rounded transition-all"
              >
                <svg width="12" height="12" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
                  <circle cx="10" cy="5" r="1"/>
                  <circle cx="10" cy="10" r="1"/>
                  <circle cx="10" cy="15" r="1"/>
                </svg>
              </button>
            )}
          </div>
          {hasChildren && isExpanded && renderFolderTree(childFolders, depth + 1)}
        </div>
      );
    });
  };

  return (
    <div className="flex h-full">
      {/* Left Sidebar - Search & Filters */}
      <div className="w-72 border-r border-[var(--border)] bg-[var(--card)] flex flex-col flex-shrink-0">
        {/* Search Box */}
        <div className="p-4 border-b border-[var(--border)]">
          <div className="relative">
            <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2" className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted-foreground)]">
              <circle cx="9" cy="9" r="6"/>
              <path d="M15 15l-3-3" strokeLinecap="round"/>
            </svg>
            <input
              type="text"
              placeholder="Search spec sheets..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full pl-9 pr-3 py-2 text-sm border border-[var(--border)] rounded-lg focus:outline-none focus:ring-2 focus:ring-[var(--primary)] bg-[var(--background)]"
            />
            {searchQuery && (
              <button
                onClick={() => setSearchQuery('')}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-[var(--muted-foreground)] hover:text-[var(--foreground)]"
              >
                <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M6 6l8 8M14 6l-8 8" strokeLinecap="round"/>
                </svg>
              </button>
            )}
          </div>
        </div>

        <div className="flex-1 overflow-y-auto">
          {/* Tags Section */}
          <div className="border-b border-[var(--border)]">
            <button
              onClick={() => toggleSection('tags')}
              className="w-full flex items-center justify-between px-4 py-3 text-sm font-medium text-[var(--foreground)] hover:bg-[var(--muted)]/50 transition-colors"
            >
              <span>Tags</span>
              <svg
                width="14"
                height="14"
                viewBox="0 0 20 20"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                className={`transition-transform ${sectionsExpanded.tags ? 'rotate-180' : ''}`}
              >
                <path d="M5 8l5 5 5-5" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </button>
            {sectionsExpanded.tags && (
              <div className="px-4 pb-3">
                {allCategories.length === 0 ? (
                  <p className="text-xs text-[var(--muted-foreground)] py-2">No categories available</p>
                ) : (
                  <div className="flex flex-wrap gap-1.5">
                    {allCategories.map(cat => {
                      const isSelected = selectedTags.includes(cat);
                      const count = allSpecSheets.filter(s => s.categories?.includes(cat)).length;
                      return (
                        <button
                          key={cat}
                          onClick={() => {
                            if (isSelected) {
                              setSelectedTags(selectedTags.filter(t => t !== cat));
                            } else {
                              setSelectedTags([...selectedTags, cat]);
                              // Reset manufacturer and folder filters to show all matching sheets
                              setSelectedManufacturerId(null);
                              setSelectedFolderId(null);
                            }
                          }}
                          className={`inline-flex items-center gap-1 px-2 py-1 text-xs rounded-full transition-colors ${
                            isSelected
                              ? 'bg-[var(--primary)] text-white'
                              : 'bg-[var(--muted)] text-[var(--muted-foreground)] hover:bg-[var(--muted)]/80'
                          }`}
                        >
                          {specSheetCategoryLabels[cat] || cat}
                          <span className={`${isSelected ? 'text-white/70' : 'text-[var(--muted-foreground)]/70'}`}>
                            {count}
                          </span>
                        </button>
                      );
                    })}
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Highlights Section */}
          <div className="border-b border-[var(--border)]">
            <button
              onClick={() => toggleSection('highlights')}
              className="w-full flex items-center justify-between px-4 py-3 text-sm font-medium text-[var(--foreground)] hover:bg-[var(--muted)]/50 transition-colors"
            >
              <span>Highlights</span>
              <svg
                width="14"
                height="14"
                viewBox="0 0 20 20"
                fill="none"
                stroke="currentColor"
                strokeWidth="2"
                className={`transition-transform ${sectionsExpanded.highlights ? 'rotate-180' : ''}`}
              >
                <path d="M5 8l5 5 5-5" strokeLinecap="round" strokeLinejoin="round"/>
              </svg>
            </button>
            {sectionsExpanded.highlights && (
              <div className="px-4 pb-3 space-y-1">
                <button
                  onClick={() => setHighlightFilter('all')}
                  className={`w-full flex items-center gap-2 px-3 py-2 text-sm rounded-lg transition-colors ${
                    highlightFilter === 'all' ? 'bg-[var(--muted)] font-medium' : 'hover:bg-[var(--muted)]/50'
                  }`}
                >
                  <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5">
                    <rect x="3" y="3" width="14" height="14" rx="2"/>
                    <path d="M7 7h6M7 10h6M7 13h4"/>
                  </svg>
                  <span className="flex-1 text-left">All Sheets</span>
                  <span className="text-xs text-[var(--muted-foreground)]">{allSpecSheets.length}</span>
                </button>
                <button
                  onClick={() => {
                    setHighlightFilter('highlighted');
                    // Reset manufacturer and folder filters to show all matching sheets
                    setSelectedManufacturerId(null);
                    setSelectedFolderId(null);
                  }}
                  className={`w-full flex items-center gap-2 px-3 py-2 text-sm rounded-lg transition-colors ${
                    highlightFilter === 'highlighted' ? 'bg-green-100 text-green-700 font-medium' : 'hover:bg-[var(--muted)]/50'
                  }`}
                >
                  <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-green-600">
                    <path d="M9 12l2 2 4-4"/>
                    <rect x="3" y="3" width="14" height="14" rx="2"/>
                  </svg>
                  <span className="flex-1 text-left">With Highlights</span>
                  <span className={`text-xs ${highlightFilter === 'highlighted' ? 'text-green-600' : 'text-[var(--muted-foreground)]'}`}>
                    {allSpecSheets.filter(s => (s.highlightCount || 0) > 0).length}
                  </span>
                </button>
                <button
                  onClick={() => {
                    setHighlightFilter('not_highlighted');
                    // Reset manufacturer and folder filters to show all matching sheets
                    setSelectedManufacturerId(null);
                    setSelectedFolderId(null);
                  }}
                  className={`w-full flex items-center gap-2 px-3 py-2 text-sm rounded-lg transition-colors ${
                    highlightFilter === 'not_highlighted' ? 'bg-orange-100 text-orange-700 font-medium' : 'hover:bg-[var(--muted)]/50'
                  }`}
                >
                  <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-orange-500">
                    <rect x="3" y="3" width="14" height="14" rx="2"/>
                    <path d="M7 10h6"/>
                  </svg>
                  <span className="flex-1 text-left">Without Highlights</span>
                  <span className={`text-xs ${highlightFilter === 'not_highlighted' ? 'text-orange-600' : 'text-[var(--muted-foreground)]'}`}>
                    {allSpecSheets.filter(s => (s.highlightCount || 0) === 0).length}
                  </span>
                </button>
              </div>
            )}
          </div>

          {/* Manufacturers Section */}
          <div>
            <div className="flex items-center justify-between px-4 py-3 hover:bg-[var(--muted)]/50 transition-colors">
              <button
                onClick={() => toggleSection('manufacturers')}
                className="flex items-center gap-2 text-sm font-medium text-[var(--foreground)]"
              >
                <span>Manufacturers</span>
                <svg
                  width="14"
                  height="14"
                  viewBox="0 0 20 20"
                  fill="none"
                  stroke="currentColor"
                  strokeWidth="2"
                  className={`transition-transform ${sectionsExpanded.manufacturers ? 'rotate-180' : ''}`}
                >
                  <path d="M5 8l5 5 5-5" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
              </button>
              <button
                onClick={(e) => {
                  e.stopPropagation();
                  setShowManufacturerModal(true);
                }}
                className="p-1 hover:bg-[var(--muted)] rounded transition-colors text-[var(--muted-foreground)] hover:text-[var(--foreground)]"
                title="Manage manufacturers"
              >
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M11 4H4a2 2 0 00-2 2v14a2 2 0 002 2h14a2 2 0 002-2v-7"/>
                  <path d="M18.5 2.5a2.121 2.121 0 013 3L12 15l-4 1 1-4 9.5-9.5z"/>
                </svg>
              </button>
            </div>
            {sectionsExpanded.manufacturers && (
              <div className="pb-2">
                {/* All Manufacturers option */}
                <button
                  onClick={() => {
                    setSelectedManufacturerId(null);
                    setSelectedFolderId(null);
                  }}
                  className={`w-full flex items-center gap-2 px-4 py-2 text-sm hover:bg-[var(--muted)]/50 transition-colors ${
                    !selectedManufacturerId && !selectedFolderId ? 'bg-[var(--muted)] font-medium' : ''
                  }`}
                >
                  <span className="w-3" />
                  <span className="flex-1 text-left">All Manufacturers</span>
                  <span className="text-xs text-[var(--muted-foreground)] bg-[var(--muted)] px-2 py-0.5 rounded-full">
                    {isLoadingManufacturers ? '...' : allSpecSheets.length}
                  </span>
                </button>

                {isLoadingManufacturers ? (
                  <div className="px-4 py-3 text-sm text-[var(--muted-foreground)]">Loading...</div>
                ) : manufacturers.map(mfr => {
                  const isExpanded = expandedManufacturers.has(mfr.name);
                  const isSelected = selectedManufacturerId === mfr.id && !selectedFolderId;
                  const manufacturerFolders = getFoldersForManufacturer(mfr.name);
                  const count = manufacturerCounts[mfr.name] || 0;

                  return (
                    <div key={mfr.id}>
                      <div
                        onClick={() => {
                          toggleManufacturer(mfr.name);
                          setSelectedManufacturerId(mfr.id);
                          setSelectedFolderId(null);
                        }}
                        className={`w-full flex items-center gap-2 px-4 py-2 text-sm hover:bg-[var(--muted)]/50 transition-colors cursor-pointer group ${
                          isSelected ? 'bg-[var(--muted)] font-medium' : ''
                        }`}
                      >
                        <svg
                          width="12"
                          height="12"
                          viewBox="0 0 20 20"
                          fill="none"
                          stroke="currentColor"
                          strokeWidth="2"
                          className={`transition-transform flex-shrink-0 ${isExpanded ? 'rotate-90' : ''}`}
                        >
                          <path d="M7 5l5 5-5 5" strokeLinecap="round" strokeLinejoin="round"/>
                        </svg>
                        <span className="flex-1 text-left truncate">{mfr.name}</span>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            handleAddRootFolder(mfr.name, mfr.id);
                          }}
                          className="opacity-0 group-hover:opacity-100 p-0.5 hover:bg-[var(--muted)] rounded transition-all mr-1"
                          title="Add folder"
                        >
                          <svg width="12" height="12" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
                            <path d="M10 6v8M6 10h8" strokeLinecap="round"/>
                          </svg>
                        </button>
                        <span className="text-xs text-[var(--muted-foreground)] bg-[var(--muted)] px-2 py-0.5 rounded-full">
                          {count}
                        </span>
                      </div>
                      {isExpanded && (
                        <div className="bg-[var(--muted)]/30">
                          {manufacturerFolders.length > 0 && renderFolderTree(manufacturerFolders, 1)}
                          {/* Add folder button for empty manufacturers */}
                          {manufacturerFolders.length === 0 && (
                            <button
                              onClick={() => handleAddRootFolder(mfr.name, mfr.id)}
                              className="w-full flex items-center gap-2 px-3 py-1.5 text-xs text-[var(--muted-foreground)] hover:text-[var(--foreground)] hover:bg-[var(--muted)]/50 transition-colors"
                              style={{ paddingLeft: '28px' }}
                            >
                              <svg width="12" height="12" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
                                <path d="M10 6v8M6 10h8" strokeLinecap="round"/>
                              </svg>
                              Add folder
                            </button>
                          )}
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </div>

        {/* Sidebar Footer */}
        <div className="p-4 border-t border-[var(--border)]">
          <button
            onClick={() => setShowUploadModal(true)}
            className="w-full flex items-center justify-center gap-2 px-3 py-2 text-sm bg-[var(--primary)] text-white rounded-lg hover:bg-[var(--primary-hover)] transition-colors"
          >
            <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
              <path d="M10 6v8M6 10h8" strokeLinecap="round"/>
            </svg>
            Add Spec Sheet
          </button>
        </div>
      </div>

      {/* Main Content */}
      <div className="flex-1 flex flex-col min-w-0">
        {/* Header */}
        <div className="flex-shrink-0 px-6 py-4 border-b border-[var(--border)] bg-[var(--background)]">
          <div className="flex items-center justify-between">
            <div>
              <h1 className="text-xl font-semibold text-[var(--foreground)]">
                Spec Sheets
              </h1>
              <p className="text-sm text-[var(--muted-foreground)]">
                {filteredSpecSheets.length} spec sheet{filteredSpecSheets.length !== 1 ? 's' : ''}
                {selectedManufacturer ? ` from ${selectedManufacturer}` : ' from all manufacturers'}
              </p>
            </div>
            <div className="flex items-center gap-3">
              {/* Active Filters Summary */}
              {hasActiveFilters && (
                <button
                  onClick={clearFilters}
                  className="text-sm text-[var(--muted-foreground)] hover:text-[var(--foreground)] flex items-center gap-1 whitespace-nowrap"
                >
                  <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2" className="flex-shrink-0">
                    <path d="M6 6l8 8M14 6l-8 8" strokeLinecap="round"/>
                  </svg>
                  Clear filters
                </button>
              )}

              {/* View Toggle */}
              <div className="flex items-center border border-[var(--border)] rounded-lg overflow-hidden">
                <button
                  onClick={() => setViewMode('grid')}
                  className={`p-2 ${viewMode === 'grid' ? 'bg-[var(--muted)]' : 'hover:bg-[var(--muted)]/50'} transition-colors`}
                  title="Grid view"
                >
                  <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
                    <rect x="3" y="3" width="5" height="5" rx="1"/>
                    <rect x="12" y="3" width="5" height="5" rx="1"/>
                    <rect x="3" y="12" width="5" height="5" rx="1"/>
                    <rect x="12" y="12" width="5" height="5" rx="1"/>
                  </svg>
                </button>
                <button
                  onClick={() => setViewMode('list')}
                  className={`p-2 ${viewMode === 'list' ? 'bg-[var(--muted)]' : 'hover:bg-[var(--muted)]/50'} transition-colors`}
                  title="List view"
                >
                  <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M4 5h12M4 10h12M4 15h12" strokeLinecap="round"/>
                  </svg>
                </button>
              </div>

              <button
                onClick={() => setShowCatalogModal(true)}
                className="flex items-center gap-2 px-3 py-2 text-sm border border-[var(--border)] text-[var(--foreground)] rounded-lg hover:bg-[var(--muted)] transition-colors"
              >
                <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M4 4h12v12H4z" strokeLinecap="round" strokeLinejoin="round"/>
                  <path d="M4 8h12M8 4v12" strokeLinecap="round"/>
                </svg>
                Get from Open Catalog
              </button>

              <button
                onClick={() => setShowUploadModal(true)}
                className="flex items-center gap-2 px-3 py-2 text-sm bg-[var(--primary)] text-white rounded-lg hover:bg-[var(--primary-hover)] transition-colors"
              >
                <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M10 14V6M6 10l4-4 4 4" strokeLinecap="round" strokeLinejoin="round"/>
                  <path d="M3 17h14" strokeLinecap="round"/>
                </svg>
                Upload
              </button>
            </div>
          </div>
        </div>

        {/* Content Area */}
        <div className="flex-1 overflow-y-auto p-6">
          {isLoadingSpecSheets ? (
            <div className="flex flex-col items-center justify-center h-full text-center">
              <div className="w-12 h-12 border-4 border-[var(--primary)] border-t-transparent rounded-full animate-spin mb-4" />
              <p className="text-sm text-[var(--muted-foreground)]">
                {searchQuery ? 'Searching...' : 'Loading spec sheets...'}
              </p>
            </div>
          ) : apiError ? (
            <div className="flex flex-col items-center justify-center h-full text-center">
              <div className="w-16 h-16 rounded-full bg-red-100 flex items-center justify-center mb-4">
                <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-red-600">
                  <circle cx="12" cy="12" r="10"/>
                  <path d="M12 8v4M12 16h.01"/>
                </svg>
              </div>
              <h3 className="text-lg font-medium text-[var(--foreground)] mb-2">Failed to load data</h3>
              <p className="text-sm text-[var(--muted-foreground)] mb-4">
                {apiError.message || 'An error occurred while loading spec sheets'}
              </p>
              <button
                onClick={() => window.location.reload()}
                className="flex items-center gap-2 px-4 py-2 text-sm text-[var(--primary)] border border-[var(--primary)] rounded-lg hover:bg-[var(--primary)]/5 transition-colors"
              >
                <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
                  <path d="M4 4v5h5M16 16v-5h-5" strokeLinecap="round" strokeLinejoin="round"/>
                  <path d="M5.938 14.062A7.5 7.5 0 1017.5 10" strokeLinecap="round"/>
                </svg>
                Retry
              </button>
            </div>
          ) : filteredSpecSheets.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-full text-center">
              <div className="w-16 h-16 rounded-full bg-[var(--muted)] flex items-center justify-center mb-4">
                <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" className="text-[var(--muted-foreground)]">
                  <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" strokeLinecap="round" strokeLinejoin="round"/>
                  <path d="M14 2v6h6" strokeLinecap="round" strokeLinejoin="round"/>
                </svg>
              </div>
              <h3 className="text-lg font-medium text-[var(--foreground)] mb-2">No spec sheets found</h3>
              <p className="text-sm text-[var(--muted-foreground)] mb-4">
                {hasActiveFilters || searchQuery
                  ? 'Try adjusting your filters'
                  : 'Upload your first spec sheet to get started'}
              </p>
              {(hasActiveFilters || searchQuery) ? (
                <button
                  onClick={clearFilters}
                  className="flex items-center gap-2 px-4 py-2 text-sm text-[var(--primary)] border border-[var(--primary)] rounded-lg hover:bg-[var(--primary)]/5 transition-colors"
                >
                  Clear Filters
                </button>
              ) : (
                <button
                  onClick={() => setShowUploadModal(true)}
                  className="flex items-center gap-2 px-4 py-2 text-sm bg-[var(--primary)] text-white rounded-lg hover:bg-[var(--primary-hover)] transition-colors"
                >
                  <svg width="14" height="14" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
                    <path d="M10 14V6M6 10l4-4 4 4" strokeLinecap="round" strokeLinejoin="round"/>
                    <path d="M3 17h14" strokeLinecap="round"/>
                  </svg>
                  Upload Spec Sheet
                </button>
              )}
            </div>
          ) : viewMode === 'grid' ? (
            <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
              {filteredSpecSheets.map(sheet => (
                <SpecSheetCard
                  key={sheet.id}
                  specSheet={sheet}
                  highlightCount={getHighlightCount(sheet.id)}
                  onClick={() => setSelectedSpecSheet(sheet)}
                  isSelected={selectedSpecSheet?.id === sheet.id}
                />
              ))}
            </div>
          ) : (
            <div className="space-y-2">
              {filteredSpecSheets.map(sheet => (
                <SpecSheetListItem
                  key={sheet.id}
                  specSheet={sheet}
                  highlightCount={getHighlightCount(sheet.id)}
                  onClick={() => setSelectedSpecSheet(sheet)}
                  isSelected={selectedSpecSheet?.id === sheet.id}
                />
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Spec Sheet Viewer Modal */}
      {selectedSpecSheet && (
        <SpecSheetViewerModal
          specSheet={selectedSpecSheet}
          onClose={() => setSelectedSpecSheet(null)}
        />
      )}

      {/* Upload Modal */}
      {showUploadModal && (
        <SpecSheetUploadModal
          onClose={() => setShowUploadModal(false)}
          defaultManufacturerId={selectedManufacturer || undefined}
        />
      )}

      {/* Open Catalog Modal */}
      {showCatalogModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div
            className="absolute inset-0 bg-black/50"
            onClick={() => setShowCatalogModal(false)}
          />
          <div className="relative bg-[var(--card)] rounded-xl shadow-xl w-full max-w-md mx-4 p-6">
            <button
              onClick={() => setShowCatalogModal(false)}
              className="absolute top-4 right-4 p-1 text-[var(--muted-foreground)] hover:text-[var(--foreground)] transition-colors"
            >
              <svg width="20" height="20" viewBox="0 0 20 20" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M6 6l8 8M14 6l-8 8" strokeLinecap="round"/>
              </svg>
            </button>

            <div className="flex flex-col items-center text-center py-8">
              {/* Coming Soon Icon */}
              <div className="w-16 h-16 rounded-full bg-[var(--primary)]/10 flex items-center justify-center mb-6">
                <svg width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" className="text-[var(--primary)]">
                  <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" strokeLinecap="round"/>
                </svg>
              </div>

              <h2 className="text-lg font-semibold text-[var(--foreground)] mb-2">
                Coming Soon
              </h2>
              <p className="text-sm text-[var(--muted-foreground)] mb-4">
                Integration with Flow Connect Open Catalog is coming soon.
              </p>
              <p className="text-xs text-[var(--muted-foreground)]">
                You&apos;ll be able to import spec sheets directly from the catalog.
              </p>
            </div>
          </div>
        </div>
      )}

      {/* Folder Context Menu */}
      {contextMenu && (
        <FolderContextMenu
          folder={contextMenu.folder}
          position={contextMenu.position}
          onClose={() => setContextMenu(null)}
          onRename={() => handleRenameFolder(contextMenu.folder)}
          onDelete={() => handleDeleteFolder(contextMenu.folder)}
          onAddSubfolder={() => handleAddSubfolder(contextMenu.folder)}
        />
      )}

      {/* Add Folder Modal */}
      {showAddFolderModal && (
        <AddFolderModal
          onClose={() => setShowAddFolderModal(false)}
          newFolderParentId={newFolderParentId}
          newFolderManufacturer={newFolderManufacturer}
          newFolderName={newFolderName}
          setNewFolderName={setNewFolderName}
          handleCreateFolder={handleCreateFolder}
          isCreatingFolder={isCreatingFolder}
          folderError={folderError}
          setFolderError={setFolderError}
          folders={folders}
        />
      )}

      {/* Manufacturer Management Modal */}
      {showManufacturerModal && (
        <ManufacturerManagementModal
          onClose={() => setShowManufacturerModal(false)}
          manufacturerList={manufacturerList}
          manufacturerCounts={manufacturerCounts}
          expandedManufacturers={expandedManufacturers}
          toggleManufacturer={toggleManufacturer}
          expandedFolders={expandedFolders}
          toggleFolder={toggleFolder}
          editingManufacturerIndex={editingManufacturerIndex}
          editingManufacturerName={editingManufacturerName}
          setEditingManufacturerName={setEditingManufacturerName}
          handleRenameManufacturer={handleRenameManufacturer}
          handleSaveManufacturerRename={handleSaveManufacturerRename}
          handleDeleteManufacturer={handleDeleteManufacturer}
          handleAddManufacturer={handleAddManufacturer}
          draggedManufacturerIndex={draggedManufacturerIndex}
          dragOverIndex={dragOverIndex}
          handleDragStart={handleDragStart}
          handleDragOver={handleDragOver}
          handleDragLeave={handleDragLeave}
          handleDrop={handleDrop}
          handleDragEnd={handleDragEnd}
          getAllFoldersForManufacturer={getAllFoldersForManufacturer}
          getChildFoldersFromAll={getChildFoldersFromAll}
          getFolderCountForManufacturer={getFolderCountForManufacturer}
          getFolderSpecSheetCount={getFolderSpecSheetCount}
          editingFolderId={editingFolderId}
          editingFolderName={editingFolderName}
          setEditingFolderName={setEditingFolderName}
          handleRenameFolder={handleRenameFolder}
          handleSaveRename={handleSaveRename}
          setEditingFolderId={setEditingFolderId}
          handleDeleteFolder={handleDeleteFolder}
          handleAddSubfolder={handleAddSubfolder}
          handleAddRootFolder={handleAddRootFolder}
          draggedFolderId={draggedFolderId}
          dragOverFolderId={dragOverFolderId}
          handleFolderDragStart={handleFolderDragStart}
          handleFolderDragOver={handleFolderDragOver}
          handleFolderDragLeave={handleFolderDragLeave}
          handleFolderDrop={handleFolderDrop}
          handleFolderDragEnd={handleFolderDragEnd}
          setDragOverFolderId={setDragOverFolderId}
          folderError={folderError}
          setFolderError={setFolderError}
          isSavingFolder={isSavingFolder}
          isLoadingFolders={isLoadingFolders}
          isLoadingAllFolders={isLoadingAllFolders}
          folders={folders}
        />
      )}
    </div>
  );
}
