'use client';

// Re-export all hooks from the hooks folder
export {
  productQueryKeys,
  useProductsInfinite,
  useProducts,
  useProduct,
  useProductSearch,
  useCreateProduct,
  useUpdateProduct,
  useDeleteProduct,
  useProductUoms,
  useCreateProductUom,
  useUpdateProductUom,
  useDeleteProductUom,
  useProductCategories,
  useProductCategorySearch,
  useCreateProductCategory,
  useUpdateProductCategory,
  useDeleteProductCategory,
  useProductCpn,
  useProductCpns,
  useCreateProductCpn,
  useUpdateProductCpn,
  useDeleteProductCpn,
  useProductQuantityPricing,
  useProductQuantityPricingList,
  useCreateProductQuantityPricing,
  useUpdateProductQuantityPricing,
  useDeleteProductQuantityPricing,
  useFactorySearch,
  useCustomerSearch,
} from '../hooks';

// Re-export types for convenience
export type {
  Product,
  ProductLandingPage,
  ProductSearchResult,
  ProductCategory,
  ProductUom,
  CreateProductInput,
  UpdateProductInput,
  CreateProductCategoryInput,
  UpdateProductCategoryInput,
  CreateProductUomInput,
  UpdateProductUomInput,
  ProductLandingPageFilter,
  ProductLandingPageOrderBy,
  PaginatedProductsResult,
  FactorySearchResult,
  ProductCpn,
  ProductCpnInput,
  CustomerSearchResult,
  ProductQuantityPricing,
  ProductQuantityPricingInput,
  QuantityPricingImportInput,
  CustomerPricingImportInput,
  ProductImportItemInput,
  ProductImportInput,
  ProductImportError,
  ProductImportResult,
} from './types/productTypes';
